import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const opportunities = [
  // ============================================
  // HEALTHCARE (15 opportunities)
  // ============================================
  {
    title: 'American Hospital Association Leadership Summit',
    organization: 'American Hospital Association',
    description: 'Present on hospital administration, patient safety, healthcare policy, or operational excellence. Seeking executives, administrators, and healthcare leaders.',
    location: 'Chicago, IL',
    isRemote: false,
    eventDate: new Date('2025-07-15'),
    cfpDeadline: new Date('2025-04-01'),
    format: 'conference',
    industries: JSON.stringify(['healthcare', 'hospital administration', 'leadership']),
    compensationType: 'travel',
    compensationAmount: 1500,
    compensationDetails: 'Travel and accommodation covered for accepted speakers',
    applyUrl: 'https://example.com/aha-summit',
    source: 'manual',
  },
  {
    title: 'HIMSS Global Health Conference',
    organization: 'HIMSS',
    description: 'Share insights on health IT, digital transformation, interoperability, and healthcare cybersecurity.',
    location: 'Orlando, FL',
    isRemote: false,
    eventDate: new Date('2025-03-10'),
    cfpDeadline: new Date('2025-11-15'),
    format: 'conference',
    industries: JSON.stringify(['healthcare', 'health IT', 'technology']),
    compensationType: 'travel',
    compensationAmount: 2000,
    compensationDetails: 'Full conference pass plus travel stipend',
    applyUrl: 'https://example.com/himss-cfp',
    source: 'manual',
  },
  {
    title: 'American Nurses Association Conference',
    organization: 'American Nurses Association',
    description: 'Present on nursing practice, patient care innovations, workforce development, or nursing leadership.',
    location: 'Washington, DC',
    isRemote: true,
    eventDate: new Date('2025-06-20'),
    cfpDeadline: new Date('2025-02-28'),
    format: 'conference',
    industries: JSON.stringify(['healthcare', 'nursing', 'patient care']),
    compensationType: 'paid',
    compensationAmount: 500,
    compensationDetails: '$500 honorarium',
    applyUrl: 'https://example.com/ana-conf',
    source: 'manual',
  },
  {
    title: 'BIO International Convention',
    organization: 'Biotechnology Innovation Organization',
    description: 'Present on biotech research, drug development, gene therapy, or biomanufacturing.',
    location: 'Boston, MA',
    isRemote: false,
    eventDate: new Date('2025-06-02'),
    cfpDeadline: new Date('2025-02-15'),
    format: 'conference',
    industries: JSON.stringify(['healthcare', 'biotech', 'pharmaceutical']),
    compensationType: 'paid',
    compensationAmount: 1200,
    compensationDetails: '$1200 speaker fee',
    applyUrl: 'https://example.com/bio-convention',
    source: 'manual',
  },
  {
    title: 'American Public Health Association Annual Meeting',
    organization: 'APHA',
    description: 'Share research and insights on public health policy, epidemiology, health equity, and community health.',
    location: 'Denver, CO',
    isRemote: true,
    eventDate: new Date('2025-10-25'),
    cfpDeadline: new Date('2025-05-01'),
    format: 'conference',
    industries: JSON.stringify(['healthcare', 'public health', 'epidemiology']),
    compensationType: 'honorarium',
    compensationAmount: 400,
    compensationDetails: '$400 honorarium for accepted presenters',
    applyUrl: 'https://example.com/apha-meeting',
    source: 'manual',
  },
  {
    title: 'Telemedicine Summit',
    organization: 'American Telemedicine Association',
    description: 'Present on telehealth implementation, remote patient monitoring, virtual care delivery, and regulatory considerations.',
    location: 'Nashville, TN',
    isRemote: true,
    eventDate: new Date('2025-09-08'),
    cfpDeadline: new Date('2025-05-15'),
    format: 'conference',
    industries: JSON.stringify(['healthcare', 'telemedicine', 'technology']),
    compensationType: 'paid',
    compensationAmount: 750,
    compensationDetails: '$750 speaker honorarium',
    applyUrl: 'https://example.com/telehealth-summit',
    source: 'manual',
  },
  {
    title: 'Pharmaceutical Executive Forum',
    organization: 'Pharma Leaders Alliance',
    description: 'Discuss pharmaceutical commercialization, market access, regulatory affairs, and drug pricing strategies.',
    location: 'Philadelphia, PA',
    isRemote: false,
    eventDate: new Date('2025-11-05'),
    cfpDeadline: new Date('2025-07-01'),
    format: 'conference',
    industries: JSON.stringify(['healthcare', 'pharmaceutical', 'regulatory']),
    compensationType: 'paid',
    compensationAmount: 1500,
    compensationDetails: '$1500 speaker fee plus travel',
    applyUrl: 'https://example.com/pharma-exec',
    source: 'manual',
  },
  {
    title: 'Healthcare Quality & Safety Summit',
    organization: 'National Quality Forum',
    description: 'Present on patient safety initiatives, quality improvement, clinical outcomes, and healthcare metrics.',
    location: 'Atlanta, GA',
    isRemote: true,
    eventDate: new Date('2025-05-18'),
    cfpDeadline: new Date('2025-02-01'),
    format: 'conference',
    industries: JSON.stringify(['healthcare', 'quality improvement', 'patient safety']),
    compensationType: 'travel',
    compensationAmount: 1000,
    compensationDetails: 'Travel expenses reimbursed',
    applyUrl: 'https://example.com/quality-safety',
    source: 'manual',
  },
  {
    title: 'Mental Health America Conference',
    organization: 'Mental Health America',
    description: 'Share expertise on mental health treatment, prevention, advocacy, and community programs.',
    location: 'San Diego, CA',
    isRemote: true,
    eventDate: new Date('2025-06-12'),
    cfpDeadline: new Date('2025-03-01'),
    format: 'conference',
    industries: JSON.stringify(['healthcare', 'mental health', 'wellness']),
    compensationType: 'paid',
    compensationAmount: 600,
    compensationDetails: '$600 speaker honorarium',
    applyUrl: 'https://example.com/mha-conf',
    source: 'manual',
  },
  {
    title: 'Medical Device Innovation Summit',
    organization: 'AdvaMed',
    description: 'Present on medical device development, FDA regulations, clinical trials, and commercialization.',
    location: 'Minneapolis, MN',
    isRemote: false,
    eventDate: new Date('2025-08-20'),
    cfpDeadline: new Date('2025-04-30'),
    format: 'conference',
    industries: JSON.stringify(['healthcare', 'medical devices', 'regulatory']),
    compensationType: 'paid',
    compensationAmount: 1000,
    compensationDetails: '$1000 speaker fee',
    applyUrl: 'https://example.com/meddevice-summit',
    source: 'manual',
  },
  {
    title: 'Healthcare Administrators Podcast',
    organization: 'HealthLeaders Media',
    description: 'Share your healthcare leadership journey and insights on hospital/practice management.',
    location: null,
    isRemote: true,
    eventDate: null,
    cfpDeadline: null,
    format: 'podcast',
    industries: JSON.stringify(['healthcare', 'hospital administration', 'leadership']),
    compensationType: 'exposure',
    compensationAmount: null,
    compensationDetails: 'Reach 200k+ healthcare executives',
    applyUrl: 'https://example.com/healthleaders-podcast',
    source: 'manual',
  },
  {
    title: 'Dental Practice Summit',
    organization: 'American Dental Association',
    description: 'Present on dental practice management, clinical innovations, patient experience, and dental technology.',
    location: 'Las Vegas, NV',
    isRemote: false,
    eventDate: new Date('2025-10-15'),
    cfpDeadline: new Date('2025-06-01'),
    format: 'conference',
    industries: JSON.stringify(['healthcare', 'dental', 'practice management']),
    compensationType: 'travel',
    compensationAmount: 1200,
    compensationDetails: 'Travel and accommodation covered',
    applyUrl: 'https://example.com/ada-summit',
    source: 'manual',
  },
  {
    title: 'Senior Care Leadership Conference',
    organization: 'American Health Care Association',
    description: 'Discuss senior care facilities, aging services, workforce challenges, and regulatory compliance.',
    location: 'Phoenix, AZ',
    isRemote: true,
    eventDate: new Date('2025-09-22'),
    cfpDeadline: new Date('2025-05-30'),
    format: 'conference',
    industries: JSON.stringify(['healthcare', 'senior care', 'long-term care']),
    compensationType: 'paid',
    compensationAmount: 700,
    compensationDetails: '$700 honorarium',
    applyUrl: 'https://example.com/ahca-conf',
    source: 'manual',
  },
  {
    title: 'Healthcare Data Analytics Summit',
    organization: 'Health Catalyst',
    description: 'Present on healthcare analytics, population health management, and clinical decision support.',
    location: 'Salt Lake City, UT',
    isRemote: true,
    eventDate: new Date('2025-04-08'),
    cfpDeadline: new Date('2025-01-15'),
    format: 'conference',
    industries: JSON.stringify(['healthcare', 'data analytics', 'technology']),
    compensationType: 'paid',
    compensationAmount: 850,
    compensationDetails: '$850 speaker fee',
    applyUrl: 'https://example.com/hc-analytics',
    source: 'manual',
  },
  {
    title: 'Physical Therapy Excellence Conference',
    organization: 'American Physical Therapy Association',
    description: 'Share expertise on physical therapy practice, rehabilitation innovations, and patient outcomes.',
    location: 'Indianapolis, IN',
    isRemote: true,
    eventDate: new Date('2025-07-28'),
    cfpDeadline: new Date('2025-04-15'),
    format: 'conference',
    industries: JSON.stringify(['healthcare', 'physical therapy', 'rehabilitation']),
    compensationType: 'honorarium',
    compensationAmount: 500,
    compensationDetails: '$500 speaker appreciation',
    applyUrl: 'https://example.com/apta-conf',
    source: 'manual',
  },

  // ============================================
  // FINANCE & BANKING (15 opportunities)
  // ============================================
  {
    title: 'American Bankers Association Annual Convention',
    organization: 'American Bankers Association',
    description: 'Present on banking regulations, fintech partnerships, digital transformation, and customer experience.',
    location: 'San Diego, CA',
    isRemote: false,
    eventDate: new Date('2025-10-12'),
    cfpDeadline: new Date('2025-06-01'),
    format: 'conference',
    industries: JSON.stringify(['finance', 'banking', 'regulatory']),
    compensationType: 'paid',
    compensationAmount: 1500,
    compensationDetails: '$1500 speaker honorarium',
    applyUrl: 'https://example.com/aba-convention',
    source: 'manual',
  },
  {
    title: 'CFA Institute Annual Conference',
    organization: 'CFA Institute',
    description: 'Share insights on investment management, portfolio strategy, ESG investing, and market analysis.',
    location: 'Chicago, IL',
    isRemote: true,
    eventDate: new Date('2025-05-18'),
    cfpDeadline: new Date('2025-01-31'),
    format: 'conference',
    industries: JSON.stringify(['finance', 'investment management', 'asset management']),
    compensationType: 'honorarium',
    compensationAmount: 750,
    compensationDetails: '$750 speaker honorarium',
    applyUrl: 'https://example.com/cfa-annual',
    source: 'manual',
  },
  {
    title: 'FinTech Connect USA',
    organization: 'FinTech Association',
    description: 'Present on payments innovation, digital banking, blockchain, and financial inclusion.',
    location: 'New York, NY',
    isRemote: false,
    eventDate: new Date('2025-09-15'),
    cfpDeadline: new Date('2025-05-15'),
    format: 'conference',
    industries: JSON.stringify(['finance', 'fintech', 'technology']),
    compensationType: 'paid',
    compensationAmount: 1200,
    compensationDetails: '$1200 speaker fee plus travel',
    applyUrl: 'https://example.com/fintech-connect',
    source: 'manual',
  },
  {
    title: 'Insurance Innovation Summit',
    organization: 'Insurance Industry Association',
    description: 'Discuss insurtech, claims automation, underwriting innovation, and customer experience.',
    location: 'Hartford, CT',
    isRemote: true,
    eventDate: new Date('2025-06-25'),
    cfpDeadline: new Date('2025-03-15'),
    format: 'conference',
    industries: JSON.stringify(['finance', 'insurance', 'insurtech']),
    compensationType: 'paid',
    compensationAmount: 1000,
    compensationDetails: '$1000 speaker fee',
    applyUrl: 'https://example.com/insurance-summit',
    source: 'manual',
  },
  {
    title: 'Credit Union National Conference',
    organization: 'CUNA',
    description: 'Present on credit union operations, member services, digital transformation, and community impact.',
    location: 'Denver, CO',
    isRemote: false,
    eventDate: new Date('2025-07-08'),
    cfpDeadline: new Date('2025-03-30'),
    format: 'conference',
    industries: JSON.stringify(['finance', 'credit unions', 'banking']),
    compensationType: 'travel',
    compensationAmount: 1200,
    compensationDetails: 'Travel and accommodation provided',
    applyUrl: 'https://example.com/cuna-conf',
    source: 'manual',
  },
  {
    title: 'Wealth Management Summit',
    organization: 'Financial Planning Association',
    description: 'Share expertise on wealth planning, retirement strategies, tax planning, and client relationships.',
    location: 'Scottsdale, AZ',
    isRemote: true,
    eventDate: new Date('2025-11-02'),
    cfpDeadline: new Date('2025-07-01'),
    format: 'conference',
    industries: JSON.stringify(['finance', 'wealth management', 'financial planning']),
    compensationType: 'paid',
    compensationAmount: 900,
    compensationDetails: '$900 honorarium',
    applyUrl: 'https://example.com/wealth-summit',
    source: 'manual',
  },
  {
    title: 'Commercial Lending Conference',
    organization: 'Risk Management Association',
    description: 'Discuss commercial lending practices, credit risk, portfolio management, and regulatory compliance.',
    location: 'Philadelphia, PA',
    isRemote: false,
    eventDate: new Date('2025-04-22'),
    cfpDeadline: new Date('2025-01-15'),
    format: 'conference',
    industries: JSON.stringify(['finance', 'banking', 'commercial lending']),
    compensationType: 'travel',
    compensationAmount: 1000,
    compensationDetails: 'Travel expenses covered',
    applyUrl: 'https://example.com/rma-lending',
    source: 'manual',
  },
  {
    title: 'Accounting & Finance Leaders Summit',
    organization: 'AICPA',
    description: 'Present on accounting best practices, financial reporting, audit innovation, and regulatory updates.',
    location: 'Las Vegas, NV',
    isRemote: true,
    eventDate: new Date('2025-06-15'),
    cfpDeadline: new Date('2025-03-01'),
    format: 'conference',
    industries: JSON.stringify(['finance', 'accounting', 'audit']),
    compensationType: 'paid',
    compensationAmount: 800,
    compensationDetails: '$800 speaker fee',
    applyUrl: 'https://example.com/aicpa-summit',
    source: 'manual',
  },
  {
    title: 'Private Equity Forum',
    organization: 'American Investment Council',
    description: 'Discuss deal sourcing, portfolio company operations, exit strategies, and LP relations.',
    location: 'New York, NY',
    isRemote: false,
    eventDate: new Date('2025-09-28'),
    cfpDeadline: new Date('2025-06-01'),
    format: 'conference',
    industries: JSON.stringify(['finance', 'private equity', 'investment']),
    compensationType: 'paid',
    compensationAmount: 2000,
    compensationDetails: '$2000 speaker honorarium',
    applyUrl: 'https://example.com/pe-forum',
    source: 'manual',
  },
  {
    title: 'Mortgage Banking Conference',
    organization: 'Mortgage Bankers Association',
    description: 'Present on mortgage origination, servicing, compliance, and technology solutions.',
    location: 'San Antonio, TX',
    isRemote: true,
    eventDate: new Date('2025-10-20'),
    cfpDeadline: new Date('2025-06-30'),
    format: 'conference',
    industries: JSON.stringify(['finance', 'mortgage', 'real estate']),
    compensationType: 'travel',
    compensationAmount: 1100,
    compensationDetails: 'Travel and accommodation covered',
    applyUrl: 'https://example.com/mba-conf',
    source: 'manual',
  },
  {
    title: 'Cryptocurrency & Digital Assets Summit',
    organization: 'Digital Currency Group',
    description: 'Share insights on cryptocurrency regulation, institutional adoption, and blockchain finance.',
    location: 'Miami, FL',
    isRemote: true,
    eventDate: new Date('2025-04-05'),
    cfpDeadline: new Date('2025-01-20'),
    format: 'conference',
    industries: JSON.stringify(['finance', 'cryptocurrency', 'blockchain']),
    compensationType: 'paid',
    compensationAmount: 1000,
    compensationDetails: '$1000 speaker fee',
    applyUrl: 'https://example.com/crypto-summit',
    source: 'manual',
  },
  {
    title: 'Corporate Treasury Summit',
    organization: 'Association for Financial Professionals',
    description: 'Discuss treasury management, cash flow optimization, risk management, and working capital.',
    location: 'Washington, DC',
    isRemote: false,
    eventDate: new Date('2025-05-12'),
    cfpDeadline: new Date('2025-02-01'),
    format: 'conference',
    industries: JSON.stringify(['finance', 'treasury', 'corporate finance']),
    compensationType: 'paid',
    compensationAmount: 850,
    compensationDetails: '$850 honorarium',
    applyUrl: 'https://example.com/afp-treasury',
    source: 'manual',
  },
  {
    title: 'Banking Compliance Conference',
    organization: 'American Bankers Association',
    description: 'Present on regulatory compliance, AML/BSA, consumer protection, and risk management.',
    location: 'Nashville, TN',
    isRemote: true,
    eventDate: new Date('2025-08-18'),
    cfpDeadline: new Date('2025-05-01'),
    format: 'conference',
    industries: JSON.stringify(['finance', 'banking', 'compliance']),
    compensationType: 'paid',
    compensationAmount: 750,
    compensationDetails: '$750 speaker fee',
    applyUrl: 'https://example.com/aba-compliance',
    source: 'manual',
  },
  {
    title: 'FinTech Founders Podcast',
    organization: 'FinTech Weekly',
    description: 'Discuss your fintech journey, challenges, and insights for founders and investors.',
    location: null,
    isRemote: true,
    eventDate: null,
    cfpDeadline: null,
    format: 'podcast',
    industries: JSON.stringify(['finance', 'fintech', 'startups']),
    compensationType: 'exposure',
    compensationAmount: null,
    compensationDetails: '150k+ listener reach',
    applyUrl: 'https://example.com/fintech-podcast',
    source: 'manual',
  },
  {
    title: 'Financial Services Diversity Summit',
    organization: 'Financial Services Roundtable',
    description: 'Present on DEI initiatives, inclusive hiring, supplier diversity, and leadership development.',
    location: 'Atlanta, GA',
    isRemote: true,
    eventDate: new Date('2025-03-25'),
    cfpDeadline: new Date('2025-12-15'),
    format: 'conference',
    industries: JSON.stringify(['finance', 'diversity', 'leadership']),
    compensationType: 'honorarium',
    compensationAmount: 500,
    compensationDetails: '$500 speaker appreciation',
    applyUrl: 'https://example.com/fs-diversity',
    source: 'manual',
  },

  // ============================================
  // ENERGY (12 opportunities)
  // ============================================
  {
    title: 'CERAWeek Energy Conference',
    organization: 'S&P Global',
    description: 'Present on energy markets, geopolitics, technology innovation, and energy transition strategies.',
    location: 'Houston, TX',
    isRemote: false,
    eventDate: new Date('2025-03-10'),
    cfpDeadline: new Date('2025-11-30'),
    format: 'conference',
    industries: JSON.stringify(['energy', 'oil and gas', 'renewable']),
    compensationType: 'paid',
    compensationAmount: 2500,
    compensationDetails: '$2500 speaker honorarium plus travel',
    applyUrl: 'https://example.com/ceraweek',
    source: 'manual',
  },
  {
    title: 'Solar Power International',
    organization: 'Solar Energy Industries Association',
    description: 'Share expertise on solar technology, project development, policy, and grid integration.',
    location: 'Anaheim, CA',
    isRemote: false,
    eventDate: new Date('2025-09-08'),
    cfpDeadline: new Date('2025-05-01'),
    format: 'conference',
    industries: JSON.stringify(['energy', 'solar', 'renewable']),
    compensationType: 'travel',
    compensationAmount: 1500,
    compensationDetails: 'Full travel and accommodation covered',
    applyUrl: 'https://example.com/spi-solar',
    source: 'manual',
  },
  {
    title: 'Wind Energy Summit',
    organization: 'American Wind Energy Association',
    description: 'Present on wind technology, offshore wind, supply chain, and project financing.',
    location: 'Dallas, TX',
    isRemote: true,
    eventDate: new Date('2025-05-20'),
    cfpDeadline: new Date('2025-02-15'),
    format: 'conference',
    industries: JSON.stringify(['energy', 'wind', 'renewable']),
    compensationType: 'paid',
    compensationAmount: 1000,
    compensationDetails: '$1000 speaker fee',
    applyUrl: 'https://example.com/awea-wind',
    source: 'manual',
  },
  {
    title: 'Electric Utility Conference',
    organization: 'Edison Electric Institute',
    description: 'Discuss grid modernization, utility business models, customer engagement, and clean energy transition.',
    location: 'Washington, DC',
    isRemote: false,
    eventDate: new Date('2025-06-08'),
    cfpDeadline: new Date('2025-03-01'),
    format: 'conference',
    industries: JSON.stringify(['energy', 'utilities', 'grid']),
    compensationType: 'travel',
    compensationAmount: 1200,
    compensationDetails: 'Travel expenses covered',
    applyUrl: 'https://example.com/eei-conf',
    source: 'manual',
  },
  {
    title: 'Energy Storage Summit',
    organization: 'Energy Storage Association',
    description: 'Present on battery technology, grid storage, behind-the-meter solutions, and market design.',
    location: 'Phoenix, AZ',
    isRemote: true,
    eventDate: new Date('2025-04-15'),
    cfpDeadline: new Date('2025-01-15'),
    format: 'conference',
    industries: JSON.stringify(['energy', 'storage', 'technology']),
    compensationType: 'paid',
    compensationAmount: 900,
    compensationDetails: '$900 honorarium',
    applyUrl: 'https://example.com/storage-summit',
    source: 'manual',
  },
  {
    title: 'Natural Gas Forum',
    organization: 'American Gas Association',
    description: 'Discuss natural gas markets, infrastructure, safety, and sustainability initiatives.',
    location: 'Houston, TX',
    isRemote: false,
    eventDate: new Date('2025-10-05'),
    cfpDeadline: new Date('2025-06-15'),
    format: 'conference',
    industries: JSON.stringify(['energy', 'natural gas', 'utilities']),
    compensationType: 'paid',
    compensationAmount: 1100,
    compensationDetails: '$1100 speaker fee',
    applyUrl: 'https://example.com/aga-forum',
    source: 'manual',
  },
  {
    title: 'Clean Energy Finance Summit',
    organization: 'Clean Energy Finance Forum',
    description: 'Present on project finance, tax equity, green bonds, and investment trends in clean energy.',
    location: 'New York, NY',
    isRemote: true,
    eventDate: new Date('2025-11-12'),
    cfpDeadline: new Date('2025-07-30'),
    format: 'conference',
    industries: JSON.stringify(['energy', 'finance', 'renewable']),
    compensationType: 'paid',
    compensationAmount: 1500,
    compensationDetails: '$1500 speaker honorarium',
    applyUrl: 'https://example.com/cef-summit',
    source: 'manual',
  },
  {
    title: 'Hydrogen Economy Conference',
    organization: 'Fuel Cell & Hydrogen Energy Association',
    description: 'Share insights on hydrogen production, fuel cells, transportation applications, and policy.',
    location: 'Los Angeles, CA',
    isRemote: true,
    eventDate: new Date('2025-08-25'),
    cfpDeadline: new Date('2025-05-01'),
    format: 'conference',
    industries: JSON.stringify(['energy', 'hydrogen', 'clean tech']),
    compensationType: 'travel',
    compensationAmount: 1000,
    compensationDetails: 'Travel stipend provided',
    applyUrl: 'https://example.com/hydrogen-conf',
    source: 'manual',
  },
  {
    title: 'Oil & Gas Technology Summit',
    organization: 'Society of Petroleum Engineers',
    description: 'Present on drilling technology, production optimization, digital oilfield, and sustainability.',
    location: 'Houston, TX',
    isRemote: false,
    eventDate: new Date('2025-09-18'),
    cfpDeadline: new Date('2025-05-30'),
    format: 'conference',
    industries: JSON.stringify(['energy', 'oil and gas', 'technology']),
    compensationType: 'paid',
    compensationAmount: 1200,
    compensationDetails: '$1200 speaker fee',
    applyUrl: 'https://example.com/spe-tech',
    source: 'manual',
  },
  {
    title: 'Nuclear Energy Summit',
    organization: 'Nuclear Energy Institute',
    description: 'Discuss nuclear technology, plant operations, advanced reactors, and workforce development.',
    location: 'Charlotte, NC',
    isRemote: false,
    eventDate: new Date('2025-07-15'),
    cfpDeadline: new Date('2025-04-01'),
    format: 'conference',
    industries: JSON.stringify(['energy', 'nuclear', 'utilities']),
    compensationType: 'travel',
    compensationAmount: 1300,
    compensationDetails: 'Full travel coverage',
    applyUrl: 'https://example.com/nei-summit',
    source: 'manual',
  },
  {
    title: 'Energy Professionals Podcast',
    organization: 'Energy Central',
    description: 'Share your energy industry expertise and career insights with our professional audience.',
    location: null,
    isRemote: true,
    eventDate: null,
    cfpDeadline: null,
    format: 'podcast',
    industries: JSON.stringify(['energy', 'utilities', 'renewable']),
    compensationType: 'exposure',
    compensationAmount: null,
    compensationDetails: '100k+ energy professional listeners',
    applyUrl: 'https://example.com/energy-podcast',
    source: 'manual',
  },
  {
    title: 'EV Infrastructure Summit',
    organization: 'Electric Vehicle Charging Association',
    description: 'Present on charging infrastructure, fleet electrification, utility programs, and policy.',
    location: 'San Francisco, CA',
    isRemote: true,
    eventDate: new Date('2025-06-02'),
    cfpDeadline: new Date('2025-02-28'),
    format: 'conference',
    industries: JSON.stringify(['energy', 'electric vehicles', 'infrastructure']),
    compensationType: 'paid',
    compensationAmount: 800,
    compensationDetails: '$800 speaker fee',
    applyUrl: 'https://example.com/ev-infra',
    source: 'manual',
  },

  // ============================================
  // MARKETING & ADVERTISING (12 opportunities)
  // ============================================
  {
    title: 'ANA Masters of Marketing',
    organization: 'Association of National Advertisers',
    description: 'Present on brand strategy, marketing effectiveness, media innovation, and consumer insights.',
    location: 'Orlando, FL',
    isRemote: false,
    eventDate: new Date('2025-10-22'),
    cfpDeadline: new Date('2025-06-15'),
    format: 'conference',
    industries: JSON.stringify(['marketing', 'advertising', 'brand']),
    compensationType: 'paid',
    compensationAmount: 1500,
    compensationDetails: '$1500 speaker honorarium',
    applyUrl: 'https://example.com/ana-masters',
    source: 'manual',
  },
  {
    title: 'Content Marketing World',
    organization: 'Content Marketing Institute',
    description: 'Share expertise on content strategy, storytelling, SEO, and audience engagement.',
    location: 'Cleveland, OH',
    isRemote: true,
    eventDate: new Date('2025-09-08'),
    cfpDeadline: new Date('2025-04-15'),
    format: 'conference',
    industries: JSON.stringify(['marketing', 'content marketing', 'digital']),
    compensationType: 'travel',
    compensationAmount: 1000,
    compensationDetails: 'Travel and accommodation provided',
    applyUrl: 'https://example.com/cmworld',
    source: 'manual',
  },
  {
    title: 'Social Media Marketing World',
    organization: 'Social Media Examiner',
    description: 'Present on social media strategy, influencer marketing, and platform-specific tactics.',
    location: 'San Diego, CA',
    isRemote: false,
    eventDate: new Date('2025-03-20'),
    cfpDeadline: new Date('2025-11-15'),
    format: 'conference',
    industries: JSON.stringify(['marketing', 'social media', 'digital']),
    compensationType: 'travel',
    compensationAmount: 1200,
    compensationDetails: 'Full travel package for speakers',
    applyUrl: 'https://example.com/smmw',
    source: 'manual',
  },
  {
    title: 'B2B Marketing Exchange',
    organization: 'Demand Gen Report',
    description: 'Discuss demand generation, account-based marketing, sales alignment, and marketing technology.',
    location: 'Scottsdale, AZ',
    isRemote: true,
    eventDate: new Date('2025-02-24'),
    cfpDeadline: new Date('2025-10-30'),
    format: 'conference',
    industries: JSON.stringify(['marketing', 'b2b', 'demand generation']),
    compensationType: 'paid',
    compensationAmount: 900,
    compensationDetails: '$900 speaker fee',
    applyUrl: 'https://example.com/b2bmx',
    source: 'manual',
  },
  {
    title: 'Digital Marketing Summit',
    organization: 'American Marketing Association',
    description: 'Present on digital transformation, marketing analytics, personalization, and customer journey.',
    location: 'Chicago, IL',
    isRemote: true,
    eventDate: new Date('2025-06-10'),
    cfpDeadline: new Date('2025-03-01'),
    format: 'conference',
    industries: JSON.stringify(['marketing', 'digital marketing', 'analytics']),
    compensationType: 'paid',
    compensationAmount: 800,
    compensationDetails: '$800 honorarium',
    applyUrl: 'https://example.com/ama-digital',
    source: 'manual',
  },
  {
    title: 'Brand Innovation Summit',
    organization: 'Brand Innovators',
    description: 'Share case studies on brand building, creative campaigns, and marketing innovation.',
    location: 'New York, NY',
    isRemote: false,
    eventDate: new Date('2025-05-15'),
    cfpDeadline: new Date('2025-02-01'),
    format: 'conference',
    industries: JSON.stringify(['marketing', 'brand', 'creative']),
    compensationType: 'exposure',
    compensationAmount: null,
    compensationDetails: 'VIP networking access with CMOs',
    applyUrl: 'https://example.com/brand-innovators',
    source: 'manual',
  },
  {
    title: 'Email Marketing Summit',
    organization: 'Email Experience Council',
    description: 'Present on email strategy, automation, deliverability, and privacy compliance.',
    location: 'Nashville, TN',
    isRemote: true,
    eventDate: new Date('2025-08-12'),
    cfpDeadline: new Date('2025-04-30'),
    format: 'conference',
    industries: JSON.stringify(['marketing', 'email marketing', 'digital']),
    compensationType: 'paid',
    compensationAmount: 650,
    compensationDetails: '$650 speaker fee',
    applyUrl: 'https://example.com/email-summit',
    source: 'manual',
  },
  {
    title: 'Marketing Analytics Conference',
    organization: 'Marketing Analytics Summit',
    description: 'Discuss marketing measurement, attribution, customer data platforms, and ROI optimization.',
    location: 'Las Vegas, NV',
    isRemote: true,
    eventDate: new Date('2025-04-08'),
    cfpDeadline: new Date('2025-01-15'),
    format: 'conference',
    industries: JSON.stringify(['marketing', 'analytics', 'data']),
    compensationType: 'paid',
    compensationAmount: 1000,
    compensationDetails: '$1000 speaker honorarium',
    applyUrl: 'https://example.com/ma-summit',
    source: 'manual',
  },
  {
    title: 'Advertising Week',
    organization: 'Advertising Week',
    description: 'Present on advertising trends, media buying, creative effectiveness, and industry transformation.',
    location: 'New York, NY',
    isRemote: false,
    eventDate: new Date('2025-10-06'),
    cfpDeadline: new Date('2025-06-01'),
    format: 'conference',
    industries: JSON.stringify(['marketing', 'advertising', 'media']),
    compensationType: 'exposure',
    compensationAmount: null,
    compensationDetails: 'Industry recognition and networking',
    applyUrl: 'https://example.com/adweek',
    source: 'manual',
  },
  {
    title: 'MarTech Conference',
    organization: 'MarTech',
    description: 'Share expertise on marketing technology, stack integration, and operational excellence.',
    location: 'Boston, MA',
    isRemote: true,
    eventDate: new Date('2025-09-22'),
    cfpDeadline: new Date('2025-05-15'),
    format: 'conference',
    industries: JSON.stringify(['marketing', 'martech', 'technology']),
    compensationType: 'paid',
    compensationAmount: 850,
    compensationDetails: '$850 speaker fee',
    applyUrl: 'https://example.com/martech',
    source: 'manual',
  },
  {
    title: 'CMO Podcast',
    organization: 'Marketing Leadership Network',
    description: 'Share your marketing leadership journey and insights with fellow marketing executives.',
    location: null,
    isRemote: true,
    eventDate: null,
    cfpDeadline: null,
    format: 'podcast',
    industries: JSON.stringify(['marketing', 'leadership', 'executive']),
    compensationType: 'exposure',
    compensationAmount: null,
    compensationDetails: 'Reach 75k+ marketing leaders',
    applyUrl: 'https://example.com/cmo-podcast',
    source: 'manual',
  },
  {
    title: 'PR & Communications Summit',
    organization: 'PRSA',
    description: 'Present on public relations strategy, crisis communications, media relations, and reputation.',
    location: 'Austin, TX',
    isRemote: true,
    eventDate: new Date('2025-10-28'),
    cfpDeadline: new Date('2025-07-01'),
    format: 'conference',
    industries: JSON.stringify(['marketing', 'public relations', 'communications']),
    compensationType: 'paid',
    compensationAmount: 700,
    compensationDetails: '$700 speaker honorarium',
    applyUrl: 'https://example.com/prsa-summit',
    source: 'manual',
  },

  // ============================================
  // HUMAN RESOURCES (10 opportunities)
  // ============================================
  {
    title: 'SHRM Annual Conference',
    organization: 'Society for Human Resource Management',
    description: 'Present on HR strategy, talent management, employee engagement, and workplace culture.',
    location: 'Las Vegas, NV',
    isRemote: false,
    eventDate: new Date('2025-06-29'),
    cfpDeadline: new Date('2025-02-15'),
    format: 'conference',
    industries: JSON.stringify(['hr', 'human resources', 'talent']),
    compensationType: 'travel',
    compensationAmount: 1500,
    compensationDetails: 'Full travel and conference pass',
    applyUrl: 'https://example.com/shrm-annual',
    source: 'manual',
  },
  {
    title: 'HR Technology Conference',
    organization: 'HR Tech',
    description: 'Share expertise on HR technology, HRIS implementation, and workforce analytics.',
    location: 'Las Vegas, NV',
    isRemote: true,
    eventDate: new Date('2025-09-30'),
    cfpDeadline: new Date('2025-05-31'),
    format: 'conference',
    industries: JSON.stringify(['hr', 'technology', 'hris']),
    compensationType: 'paid',
    compensationAmount: 1000,
    compensationDetails: '$1000 speaker fee',
    applyUrl: 'https://example.com/hrtech-conf',
    source: 'manual',
  },
  {
    title: 'Talent Acquisition Summit',
    organization: 'ERE Media',
    description: 'Discuss recruiting strategies, employer branding, candidate experience, and sourcing.',
    location: 'San Diego, CA',
    isRemote: false,
    eventDate: new Date('2025-04-28'),
    cfpDeadline: new Date('2025-01-31'),
    format: 'conference',
    industries: JSON.stringify(['hr', 'recruiting', 'talent acquisition']),
    compensationType: 'travel',
    compensationAmount: 1000,
    compensationDetails: 'Travel and accommodation covered',
    applyUrl: 'https://example.com/ta-summit',
    source: 'manual',
  },
  {
    title: 'Compensation & Benefits Forum',
    organization: 'WorldatWork',
    description: 'Present on compensation strategy, benefits design, pay equity, and total rewards.',
    location: 'Dallas, TX',
    isRemote: true,
    eventDate: new Date('2025-05-19'),
    cfpDeadline: new Date('2025-02-15'),
    format: 'conference',
    industries: JSON.stringify(['hr', 'compensation', 'benefits']),
    compensationType: 'paid',
    compensationAmount: 800,
    compensationDetails: '$800 honorarium',
    applyUrl: 'https://example.com/waw-forum',
    source: 'manual',
  },
  {
    title: 'Learning & Development Summit',
    organization: 'ATD',
    description: 'Share expertise on training design, leadership development, and learning technology.',
    location: 'Washington, DC',
    isRemote: true,
    eventDate: new Date('2025-05-18'),
    cfpDeadline: new Date('2025-01-15'),
    format: 'conference',
    industries: JSON.stringify(['hr', 'learning and development', 'training']),
    compensationType: 'paid',
    compensationAmount: 750,
    compensationDetails: '$750 speaker fee',
    applyUrl: 'https://example.com/atd-summit',
    source: 'manual',
  },
  {
    title: 'Employee Experience Conference',
    organization: 'Employee Experience Network',
    description: 'Discuss employee engagement, workplace culture, wellbeing, and experience design.',
    location: 'San Francisco, CA',
    isRemote: true,
    eventDate: new Date('2025-08-05'),
    cfpDeadline: new Date('2025-04-15'),
    format: 'conference',
    industries: JSON.stringify(['hr', 'employee experience', 'culture']),
    compensationType: 'paid',
    compensationAmount: 700,
    compensationDetails: '$700 honorarium',
    applyUrl: 'https://example.com/ex-conf',
    source: 'manual',
  },
  {
    title: 'Diversity, Equity & Inclusion Summit',
    organization: 'SHRM',
    description: 'Present on DEI strategy, inclusive hiring, belonging, and measuring DEI impact.',
    location: 'Atlanta, GA',
    isRemote: true,
    eventDate: new Date('2025-10-14'),
    cfpDeadline: new Date('2025-06-01'),
    format: 'conference',
    industries: JSON.stringify(['hr', 'diversity', 'inclusion']),
    compensationType: 'paid',
    compensationAmount: 600,
    compensationDetails: '$600 speaker honorarium',
    applyUrl: 'https://example.com/shrm-dei',
    source: 'manual',
  },
  {
    title: 'HR Analytics Conference',
    organization: 'People Analytics World',
    description: 'Share insights on people analytics, workforce planning, and data-driven HR.',
    location: 'Philadelphia, PA',
    isRemote: true,
    eventDate: new Date('2025-04-22'),
    cfpDeadline: new Date('2025-01-20'),
    format: 'conference',
    industries: JSON.stringify(['hr', 'analytics', 'data']),
    compensationType: 'paid',
    compensationAmount: 900,
    compensationDetails: '$900 speaker fee',
    applyUrl: 'https://example.com/hr-analytics',
    source: 'manual',
  },
  {
    title: 'HR Leaders Podcast',
    organization: 'HR Morning',
    description: 'Share your HR leadership journey and best practices with fellow HR professionals.',
    location: null,
    isRemote: true,
    eventDate: null,
    cfpDeadline: null,
    format: 'podcast',
    industries: JSON.stringify(['hr', 'leadership', 'human resources']),
    compensationType: 'exposure',
    compensationAmount: null,
    compensationDetails: 'Reach 120k+ HR professionals',
    applyUrl: 'https://example.com/hr-podcast',
    source: 'manual',
  },
  {
    title: 'Future of Work Summit',
    organization: 'Future of Work Institute',
    description: 'Discuss remote work, hybrid models, workforce transformation, and future workplace trends.',
    location: 'Austin, TX',
    isRemote: true,
    eventDate: new Date('2025-11-18'),
    cfpDeadline: new Date('2025-07-31'),
    format: 'conference',
    industries: JSON.stringify(['hr', 'future of work', 'workplace']),
    compensationType: 'paid',
    compensationAmount: 850,
    compensationDetails: '$850 honorarium',
    applyUrl: 'https://example.com/fow-summit',
    source: 'manual',
  },

  // ============================================
  // LEGAL (8 opportunities)
  // ============================================
  {
    title: 'ABA TECHSHOW',
    organization: 'American Bar Association',
    description: 'Present on legal technology, practice management, AI in law, and legal innovation.',
    location: 'Chicago, IL',
    isRemote: false,
    eventDate: new Date('2025-03-26'),
    cfpDeadline: new Date('2025-10-31'),
    format: 'conference',
    industries: JSON.stringify(['legal', 'technology', 'legaltech']),
    compensationType: 'travel',
    compensationAmount: 1000,
    compensationDetails: 'Travel expenses covered for speakers',
    applyUrl: 'https://example.com/aba-techshow',
    source: 'manual',
  },
  {
    title: 'Corporate Counsel Conference',
    organization: 'Association of Corporate Counsel',
    description: 'Share insights on in-house practice, legal operations, compliance, and risk management.',
    location: 'San Francisco, CA',
    isRemote: true,
    eventDate: new Date('2025-10-20'),
    cfpDeadline: new Date('2025-06-15'),
    format: 'conference',
    industries: JSON.stringify(['legal', 'corporate', 'compliance']),
    compensationType: 'paid',
    compensationAmount: 800,
    compensationDetails: '$800 speaker honorarium',
    applyUrl: 'https://example.com/acc-conf',
    source: 'manual',
  },
  {
    title: 'Legal Innovation Summit',
    organization: 'Legal Services Innovation Council',
    description: 'Present on legal service delivery, alternative legal providers, and access to justice.',
    location: 'New York, NY',
    isRemote: true,
    eventDate: new Date('2025-05-08'),
    cfpDeadline: new Date('2025-02-01'),
    format: 'conference',
    industries: JSON.stringify(['legal', 'innovation', 'access to justice']),
    compensationType: 'paid',
    compensationAmount: 750,
    compensationDetails: '$750 speaker fee',
    applyUrl: 'https://example.com/legal-innovation',
    source: 'manual',
  },
  {
    title: 'Compliance & Ethics Summit',
    organization: 'Society of Corporate Compliance and Ethics',
    description: 'Discuss compliance programs, ethics, investigations, and regulatory requirements.',
    location: 'Washington, DC',
    isRemote: false,
    eventDate: new Date('2025-09-28'),
    cfpDeadline: new Date('2025-05-30'),
    format: 'conference',
    industries: JSON.stringify(['legal', 'compliance', 'ethics']),
    compensationType: 'paid',
    compensationAmount: 700,
    compensationDetails: '$700 honorarium',
    applyUrl: 'https://example.com/scce-summit',
    source: 'manual',
  },
  {
    title: 'Privacy & Data Protection Conference',
    organization: 'International Association of Privacy Professionals',
    description: 'Present on data privacy regulations, GDPR, CCPA, and privacy program management.',
    location: 'Denver, CO',
    isRemote: true,
    eventDate: new Date('2025-04-02'),
    cfpDeadline: new Date('2025-01-10'),
    format: 'conference',
    industries: JSON.stringify(['legal', 'privacy', 'data protection']),
    compensationType: 'paid',
    compensationAmount: 900,
    compensationDetails: '$900 speaker fee',
    applyUrl: 'https://example.com/iapp-conf',
    source: 'manual',
  },
  {
    title: 'Law Firm Leadership Forum',
    organization: 'Legal Marketing Association',
    description: 'Share expertise on law firm management, business development, and client service.',
    location: 'Boston, MA',
    isRemote: false,
    eventDate: new Date('2025-06-18'),
    cfpDeadline: new Date('2025-03-01'),
    format: 'conference',
    industries: JSON.stringify(['legal', 'law firm management', 'business development']),
    compensationType: 'travel',
    compensationAmount: 800,
    compensationDetails: 'Travel and hotel covered',
    applyUrl: 'https://example.com/lma-forum',
    source: 'manual',
  },
  {
    title: 'Legal Ops Conference',
    organization: 'Corporate Legal Operations Consortium',
    description: 'Discuss legal operations, technology, vendor management, and efficiency.',
    location: 'Las Vegas, NV',
    isRemote: true,
    eventDate: new Date('2025-05-20'),
    cfpDeadline: new Date('2025-02-15'),
    format: 'conference',
    industries: JSON.stringify(['legal', 'legal operations', 'technology']),
    compensationType: 'paid',
    compensationAmount: 850,
    compensationDetails: '$850 honorarium',
    applyUrl: 'https://example.com/cloc-conf',
    source: 'manual',
  },
  {
    title: 'Legal Industry Podcast',
    organization: 'Legal Talk Network',
    description: 'Share your legal industry expertise and thought leadership with our professional audience.',
    location: null,
    isRemote: true,
    eventDate: null,
    cfpDeadline: null,
    format: 'podcast',
    industries: JSON.stringify(['legal', 'law', 'legal profession']),
    compensationType: 'exposure',
    compensationAmount: null,
    compensationDetails: 'Reach 80k+ legal professionals',
    applyUrl: 'https://example.com/legal-podcast',
    source: 'manual',
  },

  // ============================================
  // REAL ESTATE (8 opportunities)
  // ============================================
  {
    title: 'NAR Annual Conference',
    organization: 'National Association of Realtors',
    description: 'Present on real estate market trends, technology, brokerage operations, and agent success.',
    location: 'Boston, MA',
    isRemote: false,
    eventDate: new Date('2025-11-07'),
    cfpDeadline: new Date('2025-06-30'),
    format: 'conference',
    industries: JSON.stringify(['real estate', 'residential', 'brokerage']),
    compensationType: 'travel',
    compensationAmount: 1200,
    compensationDetails: 'Travel and accommodation provided',
    applyUrl: 'https://example.com/nar-annual',
    source: 'manual',
  },
  {
    title: 'Commercial Real Estate Summit',
    organization: 'NAIOP',
    description: 'Share insights on commercial development, office markets, industrial real estate, and investment.',
    location: 'Dallas, TX',
    isRemote: true,
    eventDate: new Date('2025-06-02'),
    cfpDeadline: new Date('2025-02-28'),
    format: 'conference',
    industries: JSON.stringify(['real estate', 'commercial', 'development']),
    compensationType: 'paid',
    compensationAmount: 1000,
    compensationDetails: '$1000 speaker fee',
    applyUrl: 'https://example.com/naiop-summit',
    source: 'manual',
  },
  {
    title: 'PropTech Innovation Conference',
    organization: 'Real Estate Tech Council',
    description: 'Present on property technology, smart buildings, and real estate innovation.',
    location: 'Miami, FL',
    isRemote: true,
    eventDate: new Date('2025-05-05'),
    cfpDeadline: new Date('2025-02-15'),
    format: 'conference',
    industries: JSON.stringify(['real estate', 'proptech', 'technology']),
    compensationType: 'paid',
    compensationAmount: 800,
    compensationDetails: '$800 speaker fee',
    applyUrl: 'https://example.com/proptech-conf',
    source: 'manual',
  },
  {
    title: 'Multifamily Housing Summit',
    organization: 'National Multifamily Housing Council',
    description: 'Discuss apartment operations, property management, resident experience, and market trends.',
    location: 'San Diego, CA',
    isRemote: false,
    eventDate: new Date('2025-06-23'),
    cfpDeadline: new Date('2025-03-15'),
    format: 'conference',
    industries: JSON.stringify(['real estate', 'multifamily', 'property management']),
    compensationType: 'travel',
    compensationAmount: 1100,
    compensationDetails: 'Travel expenses covered',
    applyUrl: 'https://example.com/nmhc-summit',
    source: 'manual',
  },
  {
    title: 'Real Estate Investment Forum',
    organization: 'Urban Land Institute',
    description: 'Share insights on real estate investment, development finance, and market analysis.',
    location: 'Washington, DC',
    isRemote: true,
    eventDate: new Date('2025-10-15'),
    cfpDeadline: new Date('2025-06-01'),
    format: 'conference',
    industries: JSON.stringify(['real estate', 'investment', 'development']),
    compensationType: 'paid',
    compensationAmount: 1200,
    compensationDetails: '$1200 honorarium',
    applyUrl: 'https://example.com/uli-forum',
    source: 'manual',
  },
  {
    title: 'Property Management Conference',
    organization: 'Institute of Real Estate Management',
    description: 'Present on property management best practices, technology, and tenant relations.',
    location: 'Chicago, IL',
    isRemote: true,
    eventDate: new Date('2025-04-14'),
    cfpDeadline: new Date('2025-01-15'),
    format: 'conference',
    industries: JSON.stringify(['real estate', 'property management', 'operations']),
    compensationType: 'paid',
    compensationAmount: 700,
    compensationDetails: '$700 speaker fee',
    applyUrl: 'https://example.com/irem-conf',
    source: 'manual',
  },
  {
    title: 'Affordable Housing Summit',
    organization: 'National Housing Conference',
    description: 'Discuss affordable housing development, policy, financing, and community impact.',
    location: 'Denver, CO',
    isRemote: true,
    eventDate: new Date('2025-09-08'),
    cfpDeadline: new Date('2025-05-15'),
    format: 'conference',
    industries: JSON.stringify(['real estate', 'affordable housing', 'policy']),
    compensationType: 'travel',
    compensationAmount: 800,
    compensationDetails: 'Travel stipend available',
    applyUrl: 'https://example.com/nhc-summit',
    source: 'manual',
  },
  {
    title: 'Real Estate Podcast',
    organization: 'BiggerPockets',
    description: 'Share your real estate investing journey and expertise with our investor audience.',
    location: null,
    isRemote: true,
    eventDate: null,
    cfpDeadline: null,
    format: 'podcast',
    industries: JSON.stringify(['real estate', 'investment', 'entrepreneurship']),
    compensationType: 'exposure',
    compensationAmount: null,
    compensationDetails: 'Reach 2M+ real estate investors',
    applyUrl: 'https://example.com/bp-podcast',
    source: 'manual',
  },

  // ============================================
  // EDUCATION (8 opportunities)
  // ============================================
  {
    title: 'ISTE Conference',
    organization: 'International Society for Technology in Education',
    description: 'Present on education technology, digital learning, and classroom innovation.',
    location: 'Philadelphia, PA',
    isRemote: false,
    eventDate: new Date('2025-06-29'),
    cfpDeadline: new Date('2025-01-31'),
    format: 'conference',
    industries: JSON.stringify(['education', 'edtech', 'k-12']),
    compensationType: 'travel',
    compensationAmount: 800,
    compensationDetails: 'Travel stipend for speakers',
    applyUrl: 'https://example.com/iste-conf',
    source: 'manual',
  },
  {
    title: 'EDUCAUSE Annual Conference',
    organization: 'EDUCAUSE',
    description: 'Share insights on higher education technology, digital transformation, and campus innovation.',
    location: 'Chicago, IL',
    isRemote: true,
    eventDate: new Date('2025-10-27'),
    cfpDeadline: new Date('2025-04-15'),
    format: 'conference',
    industries: JSON.stringify(['education', 'higher education', 'technology']),
    compensationType: 'travel',
    compensationAmount: 1000,
    compensationDetails: 'Conference pass plus travel support',
    applyUrl: 'https://example.com/educause',
    source: 'manual',
  },
  {
    title: 'ASU GSV Summit',
    organization: 'Arizona State University & GSV',
    description: 'Present on education innovation, edtech startups, and the future of learning.',
    location: 'San Diego, CA',
    isRemote: false,
    eventDate: new Date('2025-04-06'),
    cfpDeadline: new Date('2025-01-15'),
    format: 'conference',
    industries: JSON.stringify(['education', 'edtech', 'startups']),
    compensationType: 'travel',
    compensationAmount: 1200,
    compensationDetails: 'Full travel package',
    applyUrl: 'https://example.com/asugsv',
    source: 'manual',
  },
  {
    title: 'National School Boards Conference',
    organization: 'National School Boards Association',
    description: 'Discuss K-12 governance, policy, equity, and student achievement.',
    location: 'San Antonio, TX',
    isRemote: true,
    eventDate: new Date('2025-04-05'),
    cfpDeadline: new Date('2025-11-30'),
    format: 'conference',
    industries: JSON.stringify(['education', 'k-12', 'policy']),
    compensationType: 'travel',
    compensationAmount: 700,
    compensationDetails: 'Travel expenses covered',
    applyUrl: 'https://example.com/nsba-conf',
    source: 'manual',
  },
  {
    title: 'Online Learning Consortium Conference',
    organization: 'OLC',
    description: 'Present on online education, instructional design, and student success in virtual environments.',
    location: 'Orlando, FL',
    isRemote: true,
    eventDate: new Date('2025-10-13'),
    cfpDeadline: new Date('2025-05-15'),
    format: 'conference',
    industries: JSON.stringify(['education', 'online learning', 'higher education']),
    compensationType: 'paid',
    compensationAmount: 500,
    compensationDetails: '$500 honorarium',
    applyUrl: 'https://example.com/olc-conf',
    source: 'manual',
  },
  {
    title: 'Early Childhood Education Summit',
    organization: 'NAEYC',
    description: 'Share expertise on early childhood development, curriculum, and family engagement.',
    location: 'Nashville, TN',
    isRemote: true,
    eventDate: new Date('2025-11-19'),
    cfpDeadline: new Date('2025-06-01'),
    format: 'conference',
    industries: JSON.stringify(['education', 'early childhood', 'child development']),
    compensationType: 'honorarium',
    compensationAmount: 400,
    compensationDetails: '$400 speaker appreciation',
    applyUrl: 'https://example.com/naeyc-conf',
    source: 'manual',
  },
  {
    title: 'STEM Education Conference',
    organization: 'NSTA',
    description: 'Present on STEM curriculum, hands-on learning, and preparing students for STEM careers.',
    location: 'Atlanta, GA',
    isRemote: false,
    eventDate: new Date('2025-03-27'),
    cfpDeadline: new Date('2025-10-15'),
    format: 'conference',
    industries: JSON.stringify(['education', 'stem', 'science']),
    compensationType: 'travel',
    compensationAmount: 600,
    compensationDetails: 'Travel support available',
    applyUrl: 'https://example.com/nsta-conf',
    source: 'manual',
  },
  {
    title: 'Education Innovators Podcast',
    organization: 'EdSurge',
    description: 'Share your education innovation story and insights with educators and entrepreneurs.',
    location: null,
    isRemote: true,
    eventDate: null,
    cfpDeadline: null,
    format: 'podcast',
    industries: JSON.stringify(['education', 'edtech', 'innovation']),
    compensationType: 'exposure',
    compensationAmount: null,
    compensationDetails: 'Reach 150k+ education professionals',
    applyUrl: 'https://example.com/edsurge-podcast',
    source: 'manual',
  },

  // ============================================
  // ENVIRONMENT & SUSTAINABILITY (10 opportunities)
  // ============================================
  {
    title: 'GreenBiz Conference',
    organization: 'GreenBiz Group',
    description: 'Present on corporate sustainability, circular economy, and sustainable business practices.',
    location: 'Phoenix, AZ',
    isRemote: false,
    eventDate: new Date('2025-02-18'),
    cfpDeadline: new Date('2025-10-15'),
    format: 'conference',
    industries: JSON.stringify(['environment', 'sustainability', 'business']),
    compensationType: 'travel',
    compensationAmount: 1200,
    compensationDetails: 'Travel and accommodation covered',
    applyUrl: 'https://example.com/greenbiz',
    source: 'manual',
  },
  {
    title: 'Sustainable Brands Conference',
    organization: 'Sustainable Brands',
    description: 'Share case studies on brand sustainability, purpose-driven marketing, and consumer engagement.',
    location: 'San Diego, CA',
    isRemote: true,
    eventDate: new Date('2025-06-09'),
    cfpDeadline: new Date('2025-02-28'),
    format: 'conference',
    industries: JSON.stringify(['environment', 'sustainability', 'marketing']),
    compensationType: 'paid',
    compensationAmount: 1000,
    compensationDetails: '$1000 speaker fee',
    applyUrl: 'https://example.com/sb-conf',
    source: 'manual',
  },
  {
    title: 'Climate Week NYC',
    organization: 'Climate Group',
    description: 'Present on climate solutions, corporate climate action, and net-zero strategies.',
    location: 'New York, NY',
    isRemote: false,
    eventDate: new Date('2025-09-22'),
    cfpDeadline: new Date('2025-05-15'),
    format: 'conference',
    industries: JSON.stringify(['environment', 'climate', 'sustainability']),
    compensationType: 'exposure',
    compensationAmount: null,
    compensationDetails: 'High-profile platform with global leaders',
    applyUrl: 'https://example.com/climate-week',
    source: 'manual',
  },
  {
    title: 'ESG Investing Summit',
    organization: 'Responsible Investor',
    description: 'Discuss ESG integration, impact measurement, shareholder engagement, and sustainable finance.',
    location: 'New York, NY',
    isRemote: true,
    eventDate: new Date('2025-06-24'),
    cfpDeadline: new Date('2025-03-15'),
    format: 'conference',
    industries: JSON.stringify(['environment', 'finance', 'esg']),
    compensationType: 'paid',
    compensationAmount: 1100,
    compensationDetails: '$1100 speaker honorarium',
    applyUrl: 'https://example.com/esg-summit',
    source: 'manual',
  },
  {
    title: 'Circular Economy Conference',
    organization: 'Ellen MacArthur Foundation',
    description: 'Present on circular business models, waste reduction, and regenerative design.',
    location: 'Chicago, IL',
    isRemote: true,
    eventDate: new Date('2025-05-12'),
    cfpDeadline: new Date('2025-02-01'),
    format: 'conference',
    industries: JSON.stringify(['environment', 'circular economy', 'sustainability']),
    compensationType: 'travel',
    compensationAmount: 900,
    compensationDetails: 'Travel stipend provided',
    applyUrl: 'https://example.com/circular-conf',
    source: 'manual',
  },
  {
    title: 'Water Summit',
    organization: 'American Water Works Association',
    description: 'Share insights on water management, conservation, infrastructure, and water security.',
    location: 'Denver, CO',
    isRemote: false,
    eventDate: new Date('2025-06-08'),
    cfpDeadline: new Date('2025-02-15'),
    format: 'conference',
    industries: JSON.stringify(['environment', 'water', 'utilities']),
    compensationType: 'travel',
    compensationAmount: 1000,
    compensationDetails: 'Travel and conference pass included',
    applyUrl: 'https://example.com/awwa-summit',
    source: 'manual',
  },
  {
    title: 'Corporate Sustainability Summit',
    organization: 'Business for Social Responsibility',
    description: 'Discuss supply chain sustainability, human rights, and corporate responsibility.',
    location: 'San Francisco, CA',
    isRemote: true,
    eventDate: new Date('2025-10-08'),
    cfpDeadline: new Date('2025-06-01'),
    format: 'conference',
    industries: JSON.stringify(['environment', 'sustainability', 'corporate responsibility']),
    compensationType: 'paid',
    compensationAmount: 800,
    compensationDetails: '$800 speaker fee',
    applyUrl: 'https://example.com/bsr-summit',
    source: 'manual',
  },
  {
    title: 'Environmental Justice Conference',
    organization: 'Environmental Justice Foundation',
    description: 'Present on environmental equity, community engagement, and justice-focused solutions.',
    location: 'Atlanta, GA',
    isRemote: true,
    eventDate: new Date('2025-04-22'),
    cfpDeadline: new Date('2025-01-31'),
    format: 'conference',
    industries: JSON.stringify(['environment', 'social justice', 'community']),
    compensationType: 'honorarium',
    compensationAmount: 500,
    compensationDetails: '$500 speaker appreciation',
    applyUrl: 'https://example.com/ej-conf',
    source: 'manual',
  },
  {
    title: 'Sustainability Leaders Podcast',
    organization: 'Green Business Network',
    description: 'Share your sustainability journey and environmental initiatives.',
    location: null,
    isRemote: true,
    eventDate: null,
    cfpDeadline: null,
    format: 'podcast',
    industries: JSON.stringify(['environment', 'sustainability', 'business']),
    compensationType: 'exposure',
    compensationAmount: null,
    compensationDetails: 'Reach 100k+ sustainability professionals',
    applyUrl: 'https://example.com/sustainability-podcast',
    source: 'manual',
  },
  {
    title: 'Conservation Summit',
    organization: 'National Wildlife Federation',
    description: 'Discuss wildlife conservation, biodiversity, and ecosystem protection strategies.',
    location: 'Washington, DC',
    isRemote: true,
    eventDate: new Date('2025-09-15'),
    cfpDeadline: new Date('2025-05-30'),
    format: 'conference',
    industries: JSON.stringify(['environment', 'conservation', 'wildlife']),
    compensationType: 'travel',
    compensationAmount: 700,
    compensationDetails: 'Travel expenses reimbursed',
    applyUrl: 'https://example.com/nwf-summit',
    source: 'manual',
  },

  // ============================================
  // RETAIL & CPG (8 opportunities)
  // ============================================
  {
    title: 'NRF Retail Big Show',
    organization: 'National Retail Federation',
    description: 'Present on retail innovation, customer experience, omnichannel strategy, and store operations.',
    location: 'New York, NY',
    isRemote: false,
    eventDate: new Date('2025-01-12'),
    cfpDeadline: new Date('2025-08-15'),
    format: 'conference',
    industries: JSON.stringify(['retail', 'technology', 'customer experience']),
    compensationType: 'paid',
    compensationAmount: 1500,
    compensationDetails: '$1500 speaker honorarium',
    applyUrl: 'https://example.com/nrf-big-show',
    source: 'manual',
  },
  {
    title: 'Shoptalk',
    organization: 'Shoptalk',
    description: 'Share insights on retail transformation, e-commerce, and consumer trends.',
    location: 'Las Vegas, NV',
    isRemote: false,
    eventDate: new Date('2025-03-23'),
    cfpDeadline: new Date('2025-10-31'),
    format: 'conference',
    industries: JSON.stringify(['retail', 'ecommerce', 'technology']),
    compensationType: 'travel',
    compensationAmount: 2000,
    compensationDetails: 'Full travel package for speakers',
    applyUrl: 'https://example.com/shoptalk',
    source: 'manual',
  },
  {
    title: 'Grocery Impact Summit',
    organization: 'Food Marketing Institute',
    description: 'Discuss grocery retail trends, food safety, supply chain, and consumer behavior.',
    location: 'Dallas, TX',
    isRemote: true,
    eventDate: new Date('2025-06-15'),
    cfpDeadline: new Date('2025-03-01'),
    format: 'conference',
    industries: JSON.stringify(['retail', 'grocery', 'cpg']),
    compensationType: 'travel',
    compensationAmount: 1100,
    compensationDetails: 'Travel and accommodation covered',
    applyUrl: 'https://example.com/fmi-summit',
    source: 'manual',
  },
  {
    title: 'E-commerce Innovation Summit',
    organization: 'Digital Commerce 360',
    description: 'Present on e-commerce strategy, conversion optimization, and digital marketing.',
    location: 'Chicago, IL',
    isRemote: true,
    eventDate: new Date('2025-05-06'),
    cfpDeadline: new Date('2025-02-01'),
    format: 'conference',
    industries: JSON.stringify(['retail', 'ecommerce', 'digital']),
    compensationType: 'paid',
    compensationAmount: 900,
    compensationDetails: '$900 speaker fee',
    applyUrl: 'https://example.com/ecom-summit',
    source: 'manual',
  },
  {
    title: 'Consumer Goods Forum',
    organization: 'Consumer Goods Forum',
    description: 'Share expertise on CPG operations, sustainability, health & wellness, and retail partnerships.',
    location: 'Boston, MA',
    isRemote: false,
    eventDate: new Date('2025-06-24'),
    cfpDeadline: new Date('2025-03-15'),
    format: 'conference',
    industries: JSON.stringify(['cpg', 'retail', 'sustainability']),
    compensationType: 'travel',
    compensationAmount: 1200,
    compensationDetails: 'Travel and hotel provided',
    applyUrl: 'https://example.com/cgf-summit',
    source: 'manual',
  },
  {
    title: 'Luxury Retail Conference',
    organization: 'Luxury Institute',
    description: 'Discuss luxury retail trends, high-net-worth consumers, and premium brand strategy.',
    location: 'Miami, FL',
    isRemote: true,
    eventDate: new Date('2025-04-28'),
    cfpDeadline: new Date('2025-01-31'),
    format: 'conference',
    industries: JSON.stringify(['retail', 'luxury', 'brand']),
    compensationType: 'paid',
    compensationAmount: 1000,
    compensationDetails: '$1000 honorarium',
    applyUrl: 'https://example.com/luxury-retail',
    source: 'manual',
  },
  {
    title: 'Supply Chain & Logistics Forum',
    organization: 'Retail Industry Leaders Association',
    description: 'Present on retail supply chain, last-mile delivery, and inventory management.',
    location: 'Phoenix, AZ',
    isRemote: true,
    eventDate: new Date('2025-09-16'),
    cfpDeadline: new Date('2025-05-31'),
    format: 'conference',
    industries: JSON.stringify(['retail', 'supply chain', 'logistics']),
    compensationType: 'paid',
    compensationAmount: 800,
    compensationDetails: '$800 speaker fee',
    applyUrl: 'https://example.com/rila-supply',
    source: 'manual',
  },
  {
    title: 'Retail Leaders Podcast',
    organization: 'Retail TouchPoints',
    description: 'Share your retail leadership journey and insights with retail professionals.',
    location: null,
    isRemote: true,
    eventDate: null,
    cfpDeadline: null,
    format: 'podcast',
    industries: JSON.stringify(['retail', 'leadership', 'business']),
    compensationType: 'exposure',
    compensationAmount: null,
    compensationDetails: 'Reach 90k+ retail executives',
    applyUrl: 'https://example.com/retail-podcast',
    source: 'manual',
  },

  // ============================================
  // MANUFACTURING (6 opportunities)
  // ============================================
  {
    title: 'Manufacturing & Technology Show',
    organization: 'Society of Manufacturing Engineers',
    description: 'Present on smart manufacturing, automation, robotics, and digital transformation.',
    location: 'Detroit, MI',
    isRemote: false,
    eventDate: new Date('2025-09-08'),
    cfpDeadline: new Date('2025-05-15'),
    format: 'conference',
    industries: JSON.stringify(['manufacturing', 'technology', 'automation']),
    compensationType: 'paid',
    compensationAmount: 1000,
    compensationDetails: '$1000 speaker fee',
    applyUrl: 'https://example.com/sme-show',
    source: 'manual',
  },
  {
    title: 'Industry 4.0 Summit',
    organization: 'Manufacturing Leadership Council',
    description: 'Discuss IoT in manufacturing, digital twins, AI applications, and smart factories.',
    location: 'Chicago, IL',
    isRemote: true,
    eventDate: new Date('2025-06-10'),
    cfpDeadline: new Date('2025-03-01'),
    format: 'conference',
    industries: JSON.stringify(['manufacturing', 'industry 4.0', 'technology']),
    compensationType: 'travel',
    compensationAmount: 1200,
    compensationDetails: 'Travel and accommodation covered',
    applyUrl: 'https://example.com/i40-summit',
    source: 'manual',
  },
  {
    title: 'Quality & Continuous Improvement Conference',
    organization: 'American Society for Quality',
    description: 'Share expertise on quality management, lean manufacturing, and process improvement.',
    location: 'Denver, CO',
    isRemote: true,
    eventDate: new Date('2025-05-04'),
    cfpDeadline: new Date('2025-01-31'),
    format: 'conference',
    industries: JSON.stringify(['manufacturing', 'quality', 'continuous improvement']),
    compensationType: 'paid',
    compensationAmount: 800,
    compensationDetails: '$800 honorarium',
    applyUrl: 'https://example.com/asq-conf',
    source: 'manual',
  },
  {
    title: 'Aerospace & Defense Manufacturing Summit',
    organization: 'Aerospace Industries Association',
    description: 'Present on aerospace manufacturing, defense technology, and supply chain excellence.',
    location: 'Seattle, WA',
    isRemote: false,
    eventDate: new Date('2025-10-20'),
    cfpDeadline: new Date('2025-06-30'),
    format: 'conference',
    industries: JSON.stringify(['manufacturing', 'aerospace', 'defense']),
    compensationType: 'paid',
    compensationAmount: 1100,
    compensationDetails: '$1100 speaker fee',
    applyUrl: 'https://example.com/aia-summit',
    source: 'manual',
  },
  {
    title: 'Food & Beverage Manufacturing Forum',
    organization: 'Food Processing Magazine',
    description: 'Discuss food production technology, safety compliance, and operational efficiency.',
    location: 'Milwaukee, WI',
    isRemote: true,
    eventDate: new Date('2025-04-15'),
    cfpDeadline: new Date('2025-01-15'),
    format: 'conference',
    industries: JSON.stringify(['manufacturing', 'food and beverage', 'operations']),
    compensationType: 'travel',
    compensationAmount: 900,
    compensationDetails: 'Travel expenses reimbursed',
    applyUrl: 'https://example.com/fb-forum',
    source: 'manual',
  },
  {
    title: 'Sustainable Manufacturing Conference',
    organization: 'National Association of Manufacturers',
    description: 'Present on manufacturing sustainability, carbon reduction, and circular manufacturing.',
    location: 'Cleveland, OH',
    isRemote: true,
    eventDate: new Date('2025-07-22'),
    cfpDeadline: new Date('2025-04-01'),
    format: 'conference',
    industries: JSON.stringify(['manufacturing', 'sustainability', 'environment']),
    compensationType: 'paid',
    compensationAmount: 750,
    compensationDetails: '$750 speaker honorarium',
    applyUrl: 'https://example.com/nam-sustain',
    source: 'manual',
  },

  // ============================================
  // AGRICULTURE (6 opportunities)
  // ============================================
  {
    title: 'World Ag Expo',
    organization: 'International Agri-Center',
    description: 'Present on agricultural technology, farming innovations, and agribusiness strategies.',
    location: 'Tulare, CA',
    isRemote: false,
    eventDate: new Date('2025-02-11'),
    cfpDeadline: new Date('2025-10-31'),
    format: 'conference',
    industries: JSON.stringify(['agriculture', 'agtech', 'farming']),
    compensationType: 'travel',
    compensationAmount: 800,
    compensationDetails: 'Travel expenses covered',
    applyUrl: 'https://example.com/world-ag',
    source: 'manual',
  },
  {
    title: 'AgTech Innovation Summit',
    organization: 'AgFunder',
    description: 'Share insights on agricultural technology, precision farming, and agtech investment.',
    location: 'San Francisco, CA',
    isRemote: true,
    eventDate: new Date('2025-06-18'),
    cfpDeadline: new Date('2025-03-15'),
    format: 'conference',
    industries: JSON.stringify(['agriculture', 'agtech', 'technology']),
    compensationType: 'paid',
    compensationAmount: 1000,
    compensationDetails: '$1000 speaker fee',
    applyUrl: 'https://example.com/agfunder-summit',
    source: 'manual',
  },
  {
    title: 'Sustainable Agriculture Conference',
    organization: 'Rodale Institute',
    description: 'Discuss organic farming, regenerative agriculture, and sustainable food systems.',
    location: 'Des Moines, IA',
    isRemote: true,
    eventDate: new Date('2025-08-20'),
    cfpDeadline: new Date('2025-05-01'),
    format: 'conference',
    industries: JSON.stringify(['agriculture', 'sustainability', 'organic']),
    compensationType: 'honorarium',
    compensationAmount: 500,
    compensationDetails: '$500 speaker appreciation',
    applyUrl: 'https://example.com/rodale-conf',
    source: 'manual',
  },
  {
    title: 'Farm Bureau Convention',
    organization: 'American Farm Bureau Federation',
    description: 'Present on farm policy, agricultural economics, and rural community development.',
    location: 'Nashville, TN',
    isRemote: false,
    eventDate: new Date('2025-01-10'),
    cfpDeadline: new Date('2025-08-31'),
    format: 'conference',
    industries: JSON.stringify(['agriculture', 'policy', 'farming']),
    compensationType: 'travel',
    compensationAmount: 700,
    compensationDetails: 'Travel and lodging covered',
    applyUrl: 'https://example.com/afbf-conv',
    source: 'manual',
  },
  {
    title: 'Livestock & Meat Industry Summit',
    organization: 'North American Meat Institute',
    description: 'Discuss livestock production, meat processing, and industry trends.',
    location: 'Kansas City, MO',
    isRemote: true,
    eventDate: new Date('2025-05-06'),
    cfpDeadline: new Date('2025-02-01'),
    format: 'conference',
    industries: JSON.stringify(['agriculture', 'livestock', 'food']),
    compensationType: 'paid',
    compensationAmount: 600,
    compensationDetails: '$600 honorarium',
    applyUrl: 'https://example.com/nami-summit',
    source: 'manual',
  },
  {
    title: 'AgriFood Tech Podcast',
    organization: 'AgriFood Network',
    description: 'Share your agricultural innovation story with farmers and agtech professionals.',
    location: null,
    isRemote: true,
    eventDate: null,
    cfpDeadline: null,
    format: 'podcast',
    industries: JSON.stringify(['agriculture', 'agtech', 'food']),
    compensationType: 'exposure',
    compensationAmount: null,
    compensationDetails: 'Reach 60k+ agriculture professionals',
    applyUrl: 'https://example.com/agrifood-podcast',
    source: 'manual',
  },

  // ============================================
  // NONPROFIT & SOCIAL IMPACT (8 opportunities)
  // ============================================
  {
    title: 'AFP ICON',
    organization: 'Association of Fundraising Professionals',
    description: 'Present on fundraising strategy, donor engagement, and nonprofit development.',
    location: 'Seattle, WA',
    isRemote: false,
    eventDate: new Date('2025-04-27'),
    cfpDeadline: new Date('2025-11-30'),
    format: 'conference',
    industries: JSON.stringify(['nonprofit', 'fundraising', 'philanthropy']),
    compensationType: 'travel',
    compensationAmount: 800,
    compensationDetails: 'Travel expenses covered for speakers',
    applyUrl: 'https://example.com/afp-icon',
    source: 'manual',
  },
  {
    title: 'Nonprofit Technology Conference',
    organization: 'NTEN',
    description: 'Share expertise on nonprofit technology, digital transformation, and data management.',
    location: 'Baltimore, MD',
    isRemote: true,
    eventDate: new Date('2025-03-25'),
    cfpDeadline: new Date('2025-10-15'),
    format: 'conference',
    industries: JSON.stringify(['nonprofit', 'technology', 'digital']),
    compensationType: 'travel',
    compensationAmount: 600,
    compensationDetails: 'Travel stipend available',
    applyUrl: 'https://example.com/ntc-conf',
    source: 'manual',
  },
  {
    title: 'Social Enterprise Summit',
    organization: 'Social Enterprise Alliance',
    description: 'Discuss social enterprise models, impact measurement, and mission-driven business.',
    location: 'Minneapolis, MN',
    isRemote: true,
    eventDate: new Date('2025-06-02'),
    cfpDeadline: new Date('2025-02-28'),
    format: 'conference',
    industries: JSON.stringify(['nonprofit', 'social enterprise', 'impact']),
    compensationType: 'honorarium',
    compensationAmount: 400,
    compensationDetails: '$400 speaker appreciation',
    applyUrl: 'https://example.com/se-summit',
    source: 'manual',
  },
  {
    title: 'Foundation Leadership Summit',
    organization: 'Council on Foundations',
    description: 'Present on grantmaking strategy, foundation operations, and philanthropic leadership.',
    location: 'Washington, DC',
    isRemote: false,
    eventDate: new Date('2025-05-19'),
    cfpDeadline: new Date('2025-02-01'),
    format: 'conference',
    industries: JSON.stringify(['nonprofit', 'philanthropy', 'foundation']),
    compensationType: 'travel',
    compensationAmount: 1000,
    compensationDetails: 'Travel and accommodation covered',
    applyUrl: 'https://example.com/cof-summit',
    source: 'manual',
  },
  {
    title: 'Impact Investing Conference',
    organization: 'Global Impact Investing Network',
    description: 'Share insights on impact investing, social returns, and sustainable finance.',
    location: 'New York, NY',
    isRemote: true,
    eventDate: new Date('2025-10-14'),
    cfpDeadline: new Date('2025-06-15'),
    format: 'conference',
    industries: JSON.stringify(['nonprofit', 'finance', 'impact investing']),
    compensationType: 'paid',
    compensationAmount: 900,
    compensationDetails: '$900 speaker honorarium',
    applyUrl: 'https://example.com/giin-conf',
    source: 'manual',
  },
  {
    title: 'Nonprofit Board Leadership Forum',
    organization: 'BoardSource',
    description: 'Discuss nonprofit governance, board effectiveness, and organizational leadership.',
    location: 'San Francisco, CA',
    isRemote: true,
    eventDate: new Date('2025-09-22'),
    cfpDeadline: new Date('2025-05-31'),
    format: 'conference',
    industries: JSON.stringify(['nonprofit', 'governance', 'leadership']),
    compensationType: 'honorarium',
    compensationAmount: 500,
    compensationDetails: '$500 speaker appreciation',
    applyUrl: 'https://example.com/boardsource',
    source: 'manual',
  },
  {
    title: 'Community Development Conference',
    organization: 'National Community Development Association',
    description: 'Present on community development, housing, economic development, and equity.',
    location: 'Denver, CO',
    isRemote: true,
    eventDate: new Date('2025-07-14'),
    cfpDeadline: new Date('2025-04-01'),
    format: 'conference',
    industries: JSON.stringify(['nonprofit', 'community development', 'housing']),
    compensationType: 'travel',
    compensationAmount: 600,
    compensationDetails: 'Travel expenses reimbursed',
    applyUrl: 'https://example.com/ncda-conf',
    source: 'manual',
  },
  {
    title: 'Nonprofit Leaders Podcast',
    organization: 'Chronicle of Philanthropy',
    description: 'Share your nonprofit leadership journey and insights with the sector.',
    location: null,
    isRemote: true,
    eventDate: null,
    cfpDeadline: null,
    format: 'podcast',
    industries: JSON.stringify(['nonprofit', 'leadership', 'philanthropy']),
    compensationType: 'exposure',
    compensationAmount: null,
    compensationDetails: 'Reach 85k+ nonprofit professionals',
    applyUrl: 'https://example.com/philanthropy-podcast',
    source: 'manual',
  },

  // ============================================
  // HOSPITALITY & TOURISM (6 opportunities)
  // ============================================
  {
    title: 'HITEC Hospitality Technology Conference',
    organization: 'HFTP',
    description: 'Present on hospitality technology, hotel operations, and guest experience innovation.',
    location: 'Minneapolis, MN',
    isRemote: false,
    eventDate: new Date('2025-06-23'),
    cfpDeadline: new Date('2025-02-28'),
    format: 'conference',
    industries: JSON.stringify(['hospitality', 'technology', 'hotels']),
    compensationType: 'travel',
    compensationAmount: 1000,
    compensationDetails: 'Travel and conference pass included',
    applyUrl: 'https://example.com/hitec',
    source: 'manual',
  },
  {
    title: 'American Hotel & Lodging Conference',
    organization: 'AHLA',
    description: 'Discuss hotel operations, workforce development, and industry advocacy.',
    location: 'Los Angeles, CA',
    isRemote: true,
    eventDate: new Date('2025-05-04'),
    cfpDeadline: new Date('2025-01-31'),
    format: 'conference',
    industries: JSON.stringify(['hospitality', 'hotels', 'lodging']),
    compensationType: 'travel',
    compensationAmount: 800,
    compensationDetails: 'Travel expenses covered',
    applyUrl: 'https://example.com/ahla-conf',
    source: 'manual',
  },
  {
    title: 'Travel Industry Summit',
    organization: 'U.S. Travel Association',
    description: 'Share insights on travel trends, destination marketing, and tourism recovery.',
    location: 'Washington, DC',
    isRemote: false,
    eventDate: new Date('2025-06-09'),
    cfpDeadline: new Date('2025-03-01'),
    format: 'conference',
    industries: JSON.stringify(['hospitality', 'travel', 'tourism']),
    compensationType: 'paid',
    compensationAmount: 900,
    compensationDetails: '$900 speaker honorarium',
    applyUrl: 'https://example.com/ustravel-summit',
    source: 'manual',
  },
  {
    title: 'Restaurant Leadership Conference',
    organization: 'National Restaurant Association',
    description: 'Present on restaurant operations, food service technology, and customer experience.',
    location: 'Phoenix, AZ',
    isRemote: true,
    eventDate: new Date('2025-03-09'),
    cfpDeadline: new Date('2025-11-15'),
    format: 'conference',
    industries: JSON.stringify(['hospitality', 'restaurant', 'food service']),
    compensationType: 'travel',
    compensationAmount: 1100,
    compensationDetails: 'Full travel package',
    applyUrl: 'https://example.com/nra-leadership',
    source: 'manual',
  },
  {
    title: 'Meetings & Events Industry Conference',
    organization: 'MPI',
    description: 'Discuss event planning, meeting design, and the business events industry.',
    location: 'Nashville, TN',
    isRemote: true,
    eventDate: new Date('2025-06-15'),
    cfpDeadline: new Date('2025-02-15'),
    format: 'conference',
    industries: JSON.stringify(['hospitality', 'events', 'meetings']),
    compensationType: 'travel',
    compensationAmount: 700,
    compensationDetails: 'Travel stipend provided',
    applyUrl: 'https://example.com/mpi-conf',
    source: 'manual',
  },
  {
    title: 'Hospitality Leaders Podcast',
    organization: 'Hotel Management Magazine',
    description: 'Share your hospitality leadership journey and industry insights.',
    location: null,
    isRemote: true,
    eventDate: null,
    cfpDeadline: null,
    format: 'podcast',
    industries: JSON.stringify(['hospitality', 'leadership', 'hotels']),
    compensationType: 'exposure',
    compensationAmount: null,
    compensationDetails: 'Reach 70k+ hospitality professionals',
    applyUrl: 'https://example.com/hotel-podcast',
    source: 'manual',
  },

];

async function main() {
  console.log('Clearing existing opportunities...');
  await prisma.opportunity.deleteMany({});

  console.log('Seeding database...');

  for (const opp of opportunities) {
    await prisma.opportunity.create({ data: opp });
  }

  console.log(`Created ${opportunities.length} opportunities`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
