import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const opportunities = [
  // TECHNOLOGY
  {
    title: 'Tech Conference 2025 - Call for Speakers',
    organization: 'TechWorld Events',
    description: 'Present on cutting-edge technology topics including AI, cloud computing, and software architecture.',
    location: 'San Francisco, CA',
    isRemote: false,
    eventDate: new Date('2025-06-15'),
    cfpDeadline: new Date('2025-03-01'),
    format: 'conference',
    industries: JSON.stringify(['technology', 'software', 'ai']),
    compensationType: 'paid',
    compensationAmount: 500,
    compensationDetails: '$500 honorarium plus travel and accommodation',
    applyUrl: 'https://example.com/tech-conf-cfp',
    source: 'manual',
  },
  {
    title: 'React Summit Remote Edition',
    organization: 'GitNation',
    description: 'Present at the largest React conference! Topics should cover React, React Native, or related ecosystem tools.',
    location: null,
    isRemote: true,
    eventDate: new Date('2025-10-05'),
    cfpDeadline: new Date('2025-06-30'),
    format: 'conference',
    industries: JSON.stringify(['technology', 'javascript', 'frontend']),
    compensationType: 'paid',
    compensationAmount: 1000,
    compensationDetails: '$1000 speaker fee',
    applyUrl: 'https://example.com/react-summit',
    source: 'manual',
  },
  {
    title: 'KubeCon North America',
    organization: 'CNCF',
    description: 'Submit proposals for talks on Kubernetes, cloud native technologies, and distributed systems.',
    location: 'Chicago, IL',
    isRemote: false,
    eventDate: new Date('2025-11-18'),
    cfpDeadline: new Date('2025-08-01'),
    format: 'conference',
    industries: JSON.stringify(['technology', 'devops', 'cloud']),
    compensationType: 'travel',
    compensationAmount: 1500,
    compensationDetails: 'Travel funding available for accepted speakers',
    applyUrl: 'https://example.com/kubecon-cfp',
    source: 'manual',
  },

  // HEALTHCARE
  {
    title: 'Healthcare Innovation Summit',
    organization: 'HealthTech Alliance',
    description: 'Share insights on digital health transformation, telemedicine, AI in diagnostics, and patient care innovations.',
    location: 'Boston, MA',
    isRemote: true,
    eventDate: new Date('2025-09-15'),
    cfpDeadline: new Date('2025-05-30'),
    format: 'conference',
    industries: JSON.stringify(['healthcare', 'technology', 'biotech']),
    compensationType: 'paid',
    compensationAmount: 750,
    compensationDetails: '$750 speaker honorarium',
    applyUrl: 'https://example.com/health-innovation',
    source: 'manual',
  },
  {
    title: 'Medical Device Conference',
    organization: 'MedTech Association',
    description: 'Present on medical device development, regulatory compliance, and clinical trials.',
    location: 'Minneapolis, MN',
    isRemote: false,
    eventDate: new Date('2025-07-20'),
    cfpDeadline: new Date('2025-04-01'),
    format: 'conference',
    industries: JSON.stringify(['healthcare', 'medical devices', 'regulatory']),
    compensationType: 'travel',
    compensationAmount: 1200,
    compensationDetails: 'Travel and accommodation covered',
    applyUrl: 'https://example.com/medtech-conf',
    source: 'manual',
  },
  {
    title: 'Mental Health Professionals Podcast',
    organization: 'Wellness Network',
    description: 'Share your expertise on mental health treatment, therapy innovations, and patient outcomes.',
    location: null,
    isRemote: true,
    eventDate: null,
    cfpDeadline: null,
    format: 'podcast',
    industries: JSON.stringify(['healthcare', 'mental health', 'wellness']),
    compensationType: 'exposure',
    compensationAmount: null,
    compensationDetails: 'Reach 200k+ healthcare professionals',
    applyUrl: 'https://example.com/mental-health-podcast',
    source: 'manual',
  },

  // ENVIRONMENT & SUSTAINABILITY
  {
    title: 'Climate Action Summit',
    organization: 'Green Future Foundation',
    description: 'Present on climate solutions, carbon reduction strategies, and sustainable business practices.',
    location: 'Seattle, WA',
    isRemote: true,
    eventDate: new Date('2025-04-22'),
    cfpDeadline: new Date('2025-02-15'),
    format: 'conference',
    industries: JSON.stringify(['environment', 'sustainability', 'climate']),
    compensationType: 'paid',
    compensationAmount: 600,
    compensationDetails: '$600 honorarium',
    applyUrl: 'https://example.com/climate-summit',
    source: 'manual',
  },
  {
    title: 'Sustainable Business Forum',
    organization: 'ESG Leaders Network',
    description: 'Share case studies on ESG implementation, sustainable supply chains, and circular economy.',
    location: 'New York, NY',
    isRemote: false,
    eventDate: new Date('2025-06-10'),
    cfpDeadline: new Date('2025-03-20'),
    format: 'conference',
    industries: JSON.stringify(['environment', 'business', 'sustainability']),
    compensationType: 'paid',
    compensationAmount: 1000,
    compensationDetails: '$1000 speaker fee plus travel',
    applyUrl: 'https://example.com/sustainable-business',
    source: 'manual',
  },

  // ENERGY
  {
    title: 'Renewable Energy Conference',
    organization: 'Clean Energy Council',
    description: 'Present on solar, wind, battery storage, and grid modernization technologies.',
    location: 'Denver, CO',
    isRemote: false,
    eventDate: new Date('2025-08-05'),
    cfpDeadline: new Date('2025-04-30'),
    format: 'conference',
    industries: JSON.stringify(['energy', 'renewable', 'technology']),
    compensationType: 'travel',
    compensationAmount: 1500,
    compensationDetails: 'Full travel and hotel covered',
    applyUrl: 'https://example.com/renewable-energy',
    source: 'manual',
  },
  {
    title: 'Oil & Gas Digital Transformation Summit',
    organization: 'Energy Innovation Institute',
    description: 'Discuss digital transformation, AI/ML applications, and operational efficiency in energy.',
    location: 'Houston, TX',
    isRemote: false,
    eventDate: new Date('2025-10-15'),
    cfpDeadline: new Date('2025-06-30'),
    format: 'conference',
    industries: JSON.stringify(['energy', 'oil and gas', 'technology']),
    compensationType: 'paid',
    compensationAmount: 2000,
    compensationDetails: '$2000 speaker fee',
    applyUrl: 'https://example.com/energy-digital',
    source: 'manual',
  },

  // CYBERSECURITY
  {
    title: 'Security BSides Los Angeles',
    organization: 'BSides LA',
    description: 'Community-driven security conference for offensive security, defensive techniques, and research.',
    location: 'Los Angeles, CA',
    isRemote: false,
    eventDate: new Date('2025-08-16'),
    cfpDeadline: new Date('2025-05-01'),
    format: 'conference',
    industries: JSON.stringify(['cybersecurity', 'technology', 'infosec']),
    compensationType: 'exposure',
    compensationAmount: null,
    compensationDetails: 'Free conference pass and swag',
    applyUrl: 'https://example.com/bsides-la',
    source: 'manual',
  },
  {
    title: 'Enterprise Security Summit',
    organization: 'CISO Alliance',
    description: 'Present on enterprise security architecture, zero trust, and incident response.',
    location: 'Washington, DC',
    isRemote: true,
    eventDate: new Date('2025-09-25'),
    cfpDeadline: new Date('2025-06-01'),
    format: 'conference',
    industries: JSON.stringify(['cybersecurity', 'enterprise', 'technology']),
    compensationType: 'paid',
    compensationAmount: 1500,
    compensationDetails: '$1500 honorarium',
    applyUrl: 'https://example.com/enterprise-security',
    source: 'manual',
  },

  // ENTERTAINMENT & MEDIA
  {
    title: 'Entertainment Industry Conference',
    organization: 'Hollywood Media Group',
    description: 'Discuss streaming trends, content creation, and entertainment technology.',
    location: 'Los Angeles, CA',
    isRemote: false,
    eventDate: new Date('2025-11-05'),
    cfpDeadline: new Date('2025-07-15'),
    format: 'conference',
    industries: JSON.stringify(['entertainment', 'media', 'streaming']),
    compensationType: 'paid',
    compensationAmount: 800,
    compensationDetails: '$800 speaker fee',
    applyUrl: 'https://example.com/entertainment-conf',
    source: 'manual',
  },
  {
    title: 'Gaming Industry Summit',
    organization: 'Game Developers Network',
    description: 'Present on game development, esports, monetization strategies, and gaming technology.',
    location: 'Los Angeles, CA',
    isRemote: true,
    eventDate: new Date('2025-06-20'),
    cfpDeadline: new Date('2025-03-15'),
    format: 'conference',
    industries: JSON.stringify(['entertainment', 'gaming', 'technology']),
    compensationType: 'travel',
    compensationAmount: 1000,
    compensationDetails: 'Travel stipend up to $1000',
    applyUrl: 'https://example.com/gaming-summit',
    source: 'manual',
  },
  {
    title: 'Content Creator Podcast',
    organization: 'Creator Economy Hub',
    description: 'Share your journey building an audience and monetizing content.',
    location: null,
    isRemote: true,
    eventDate: null,
    cfpDeadline: null,
    format: 'podcast',
    industries: JSON.stringify(['entertainment', 'media', 'marketing']),
    compensationType: 'exposure',
    compensationAmount: null,
    compensationDetails: '500k+ subscriber reach',
    applyUrl: 'https://example.com/creator-podcast',
    source: 'manual',
  },

  // CPG & RETAIL
  {
    title: 'Retail Innovation Summit',
    organization: 'National Retail Federation',
    description: 'Present on omnichannel retail, customer experience, and retail technology.',
    location: 'New York, NY',
    isRemote: false,
    eventDate: new Date('2025-01-15'),
    cfpDeadline: new Date('2025-09-30'),
    format: 'conference',
    industries: JSON.stringify(['retail', 'cpg', 'technology']),
    compensationType: 'paid',
    compensationAmount: 1200,
    compensationDetails: '$1200 speaker honorarium',
    applyUrl: 'https://example.com/retail-innovation',
    source: 'manual',
  },
  {
    title: 'Consumer Goods Forum',
    organization: 'CPG Industry Association',
    description: 'Discuss supply chain optimization, sustainability in CPG, and consumer trends.',
    location: 'Chicago, IL',
    isRemote: true,
    eventDate: new Date('2025-05-20'),
    cfpDeadline: new Date('2025-02-28'),
    format: 'conference',
    industries: JSON.stringify(['cpg', 'supply chain', 'sustainability']),
    compensationType: 'travel',
    compensationAmount: 1500,
    compensationDetails: 'Travel and accommodation provided',
    applyUrl: 'https://example.com/cpg-forum',
    source: 'manual',
  },

  // FINANCE
  {
    title: 'FinTech Innovation Summit',
    organization: 'FinTech Alliance',
    description: 'Present on payments, blockchain, digital banking, and financial inclusion.',
    location: 'London, UK',
    isRemote: false,
    eventDate: new Date('2025-09-10'),
    cfpDeadline: new Date('2025-05-01'),
    format: 'conference',
    industries: JSON.stringify(['finance', 'fintech', 'technology']),
    compensationType: 'paid',
    compensationAmount: 1200,
    compensationDetails: '£1000 speaker fee plus travel',
    applyUrl: 'https://example.com/fintech-summit',
    source: 'manual',
  },
  {
    title: 'Investment Management Conference',
    organization: 'CFA Institute',
    description: 'Share insights on portfolio management, ESG investing, and market analysis.',
    location: 'Boston, MA',
    isRemote: true,
    eventDate: new Date('2025-10-20'),
    cfpDeadline: new Date('2025-06-15'),
    format: 'conference',
    industries: JSON.stringify(['finance', 'investment', 'asset management']),
    compensationType: 'honorarium',
    compensationAmount: 500,
    compensationDetails: '$500 honorarium',
    applyUrl: 'https://example.com/investment-conf',
    source: 'manual',
  },

  // EDUCATION
  {
    title: 'EdTech Conference',
    organization: 'Education Technology Association',
    description: 'Present on learning technologies, online education, and student engagement.',
    location: 'Austin, TX',
    isRemote: true,
    eventDate: new Date('2025-07-15'),
    cfpDeadline: new Date('2025-04-01'),
    format: 'conference',
    industries: JSON.stringify(['education', 'technology', 'edtech']),
    compensationType: 'paid',
    compensationAmount: 600,
    compensationDetails: '$600 speaker honorarium',
    applyUrl: 'https://example.com/edtech-conf',
    source: 'manual',
  },
  {
    title: 'Higher Education Summit',
    organization: 'University Leaders Network',
    description: 'Discuss enrollment trends, student success, and institutional innovation.',
    location: 'Washington, DC',
    isRemote: false,
    eventDate: new Date('2025-03-25'),
    cfpDeadline: new Date('2025-01-15'),
    format: 'conference',
    industries: JSON.stringify(['education', 'higher education', 'leadership']),
    compensationType: 'travel',
    compensationAmount: 800,
    compensationDetails: 'Travel expenses covered',
    applyUrl: 'https://example.com/higher-ed-summit',
    source: 'manual',
  },

  // MANUFACTURING
  {
    title: 'Smart Manufacturing Summit',
    organization: 'Manufacturing Institute',
    description: 'Present on Industry 4.0, automation, IoT in manufacturing, and workforce development.',
    location: 'Detroit, MI',
    isRemote: false,
    eventDate: new Date('2025-09-08'),
    cfpDeadline: new Date('2025-05-15'),
    format: 'conference',
    industries: JSON.stringify(['manufacturing', 'technology', 'automation']),
    compensationType: 'paid',
    compensationAmount: 1000,
    compensationDetails: '$1000 speaker fee',
    applyUrl: 'https://example.com/smart-manufacturing',
    source: 'manual',
  },

  // TRANSPORTATION & LOGISTICS
  {
    title: 'Supply Chain & Logistics Conference',
    organization: 'Supply Chain Management Association',
    description: 'Discuss supply chain resilience, last-mile delivery, and logistics technology.',
    location: 'Atlanta, GA',
    isRemote: true,
    eventDate: new Date('2025-04-10'),
    cfpDeadline: new Date('2025-01-31'),
    format: 'conference',
    industries: JSON.stringify(['transportation', 'logistics', 'supply chain']),
    compensationType: 'travel',
    compensationAmount: 1200,
    compensationDetails: 'Travel and hotel covered',
    applyUrl: 'https://example.com/supply-chain-conf',
    source: 'manual',
  },
  {
    title: 'Autonomous Vehicle Summit',
    organization: 'Future Mobility Council',
    description: 'Present on self-driving technology, regulations, and the future of transportation.',
    location: 'San Francisco, CA',
    isRemote: false,
    eventDate: new Date('2025-11-12'),
    cfpDeadline: new Date('2025-07-30'),
    format: 'conference',
    industries: JSON.stringify(['transportation', 'automotive', 'technology']),
    compensationType: 'paid',
    compensationAmount: 1500,
    compensationDetails: '$1500 honorarium plus travel',
    applyUrl: 'https://example.com/av-summit',
    source: 'manual',
  },

  // REAL ESTATE
  {
    title: 'PropTech Conference',
    organization: 'Real Estate Technology Council',
    description: 'Discuss property technology, smart buildings, and real estate innovation.',
    location: 'Miami, FL',
    isRemote: true,
    eventDate: new Date('2025-05-05'),
    cfpDeadline: new Date('2025-02-15'),
    format: 'conference',
    industries: JSON.stringify(['real estate', 'proptech', 'technology']),
    compensationType: 'paid',
    compensationAmount: 800,
    compensationDetails: '$800 speaker fee',
    applyUrl: 'https://example.com/proptech-conf',
    source: 'manual',
  },

  // LEGAL
  {
    title: 'Legal Tech Conference',
    organization: 'Legal Innovation Institute',
    description: 'Present on AI in legal, practice management technology, and access to justice.',
    location: 'New York, NY',
    isRemote: true,
    eventDate: new Date('2025-06-25'),
    cfpDeadline: new Date('2025-03-30'),
    format: 'conference',
    industries: JSON.stringify(['legal', 'technology', 'legaltech']),
    compensationType: 'honorarium',
    compensationAmount: 750,
    compensationDetails: '$750 honorarium',
    applyUrl: 'https://example.com/legaltech-conf',
    source: 'manual',
  },

  // MARKETING
  {
    title: 'Marketing Summit',
    organization: 'American Marketing Association',
    description: 'Share insights on digital marketing, brand strategy, and marketing analytics.',
    location: 'Los Angeles, CA',
    isRemote: true,
    eventDate: new Date('2025-10-08'),
    cfpDeadline: new Date('2025-06-20'),
    format: 'conference',
    industries: JSON.stringify(['marketing', 'advertising', 'digital']),
    compensationType: 'paid',
    compensationAmount: 900,
    compensationDetails: '$900 speaker fee',
    applyUrl: 'https://example.com/marketing-summit',
    source: 'manual',
  },

  // HR & TALENT
  {
    title: 'HR Technology Conference',
    organization: 'HR Tech Association',
    description: 'Present on HR technology, talent acquisition, and employee experience.',
    location: 'Las Vegas, NV',
    isRemote: false,
    eventDate: new Date('2025-09-30'),
    cfpDeadline: new Date('2025-05-31'),
    format: 'conference',
    industries: JSON.stringify(['hr', 'technology', 'talent']),
    compensationType: 'travel',
    compensationAmount: 1000,
    compensationDetails: 'Conference pass and travel stipend',
    applyUrl: 'https://example.com/hr-tech-conf',
    source: 'manual',
  },

  // AGRICULTURE
  {
    title: 'AgTech Summit',
    organization: 'Agriculture Technology Association',
    description: 'Discuss precision agriculture, farm technology, and sustainable farming.',
    location: 'Des Moines, IA',
    isRemote: true,
    eventDate: new Date('2025-08-20'),
    cfpDeadline: new Date('2025-05-01'),
    format: 'conference',
    industries: JSON.stringify(['agriculture', 'technology', 'sustainability']),
    compensationType: 'travel',
    compensationAmount: 800,
    compensationDetails: 'Travel expenses covered',
    applyUrl: 'https://example.com/agtech-summit',
    source: 'manual',
  },

  // DATA SCIENCE
  {
    title: 'Data Science Webinar Series',
    organization: 'DataCamp',
    description: 'Host a 1-hour webinar on data science, machine learning, or analytics topics.',
    location: null,
    isRemote: true,
    eventDate: null,
    cfpDeadline: null,
    format: 'webinar',
    industries: JSON.stringify(['technology', 'data science', 'ai']),
    compensationType: 'paid',
    compensationAmount: 750,
    compensationDetails: '$750 per webinar',
    applyUrl: 'https://example.com/datacamp-webinars',
    source: 'manual',
  },

  // DIVERSITY & INCLUSION
  {
    title: 'Women in Leadership Summit',
    organization: 'Women Leaders Network',
    description: 'Share experiences and insights on leadership, career growth, and workplace equity.',
    location: 'San Francisco, CA',
    isRemote: true,
    eventDate: new Date('2025-03-08'),
    cfpDeadline: new Date('2025-01-15'),
    format: 'conference',
    industries: JSON.stringify(['diversity', 'leadership', 'career']),
    compensationType: 'honorarium',
    compensationAmount: 400,
    compensationDetails: '$400 speaker appreciation',
    applyUrl: 'https://example.com/women-leaders',
    source: 'manual',
  },

  // STARTUP & ENTREPRENEURSHIP
  {
    title: 'Startup Growth Workshop Series',
    organization: 'Founder Institute',
    description: 'Lead workshops on fundraising, product-market fit, hiring, or go-to-market strategies.',
    location: null,
    isRemote: true,
    eventDate: null,
    cfpDeadline: new Date('2025-04-30'),
    format: 'workshop',
    industries: JSON.stringify(['startups', 'entrepreneurship', 'business']),
    compensationType: 'honorarium',
    compensationAmount: 200,
    compensationDetails: '$200 per workshop',
    applyUrl: 'https://example.com/fi-workshops',
    source: 'manual',
  },

  // MEETUPS (various industries)
  {
    title: 'JavaScript Weekly Meetup',
    organization: 'JS Community NYC',
    description: 'Give a lightning talk on any JavaScript-related topic. Great for first-time speakers!',
    location: 'New York, NY',
    isRemote: false,
    eventDate: null,
    cfpDeadline: null,
    format: 'meetup',
    industries: JSON.stringify(['technology', 'javascript']),
    compensationType: 'exposure',
    compensationAmount: null,
    compensationDetails: 'Free pizza and networking',
    applyUrl: 'https://example.com/jsnyc-meetup',
    source: 'manual',
  },
  {
    title: 'Healthcare Innovators Meetup',
    organization: 'Health Tech LA',
    description: 'Present on healthcare technology, digital health, or health startup experiences.',
    location: 'Los Angeles, CA',
    isRemote: false,
    eventDate: null,
    cfpDeadline: null,
    format: 'meetup',
    industries: JSON.stringify(['healthcare', 'technology', 'startups']),
    compensationType: 'exposure',
    compensationAmount: null,
    compensationDetails: 'Networking with healthcare leaders',
    applyUrl: 'https://example.com/healthtech-la',
    source: 'manual',
  },

  // PODCASTS (various industries)
  {
    title: 'Sustainability Leaders Podcast',
    organization: 'Green Business Network',
    description: 'Share your sustainability journey and environmental initiatives.',
    location: null,
    isRemote: true,
    eventDate: null,
    cfpDeadline: null,
    format: 'podcast',
    industries: JSON.stringify(['environment', 'sustainability', 'business']),
    compensationType: 'exposure',
    compensationAmount: null,
    compensationDetails: 'Reach 100k+ sustainability professionals',
    applyUrl: 'https://example.com/sustainability-podcast',
    source: 'manual',
  },
  {
    title: 'FinTech Founders Podcast',
    organization: 'FinTech Weekly',
    description: 'Discuss your fintech journey, challenges, and insights for founders.',
    location: null,
    isRemote: true,
    eventDate: null,
    cfpDeadline: null,
    format: 'podcast',
    industries: JSON.stringify(['finance', 'fintech', 'startups']),
    compensationType: 'exposure',
    compensationAmount: null,
    compensationDetails: '150k+ listener reach',
    applyUrl: 'https://example.com/fintech-podcast',
    source: 'manual',
  },

  // HIGH COMPENSATION
  {
    title: 'AWS re:Invent Speaker Program',
    organization: 'Amazon Web Services',
    description: 'Share your AWS expertise at the largest cloud computing conference.',
    location: 'Las Vegas, NV',
    isRemote: false,
    eventDate: new Date('2025-12-01'),
    cfpDeadline: new Date('2025-07-31'),
    format: 'conference',
    industries: JSON.stringify(['technology', 'cloud', 'devops']),
    compensationType: 'travel',
    compensationAmount: 2500,
    compensationDetails: 'Full travel and accommodation covered (valued at $2500+)',
    applyUrl: 'https://example.com/reinvent-cfp',
    source: 'manual',
  },
  {
    title: "O'Reilly Software Architecture Conference",
    organization: "O'Reilly Media",
    description: 'Present on software architecture, microservices, and distributed systems.',
    location: 'New York, NY',
    isRemote: true,
    eventDate: new Date('2025-11-03'),
    cfpDeadline: new Date('2025-07-01'),
    format: 'conference',
    industries: JSON.stringify(['technology', 'architecture', 'software']),
    compensationType: 'paid',
    compensationAmount: 1500,
    compensationDetails: '$1500 speaker fee for 45-min sessions',
    applyUrl: 'https://example.com/oreilly-software-arch',
    source: 'manual',
  },
  {
    title: 'Executive Leadership Forum',
    organization: 'Chief Executive Network',
    description: 'Share C-suite insights on strategy, leadership, and organizational transformation.',
    location: 'New York, NY',
    isRemote: false,
    eventDate: new Date('2025-10-25'),
    cfpDeadline: new Date('2025-06-30'),
    format: 'panel',
    industries: JSON.stringify(['leadership', 'business', 'executive']),
    compensationType: 'paid',
    compensationAmount: 3000,
    compensationDetails: '$3000 honorarium for keynote speakers',
    applyUrl: 'https://example.com/exec-forum',
    source: 'manual',
  },
];

async function main() {
  console.log('Clearing existing opportunities...');
  await prisma.opportunity.deleteMany({});

  console.log('Seeding database...');

  for (const opp of opportunities) {
    await prisma.opportunity.create({ data: opp });
  }

  console.log(`Created ${opportunities.length} opportunities`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
